import type { SeedProduct } from './types.js';

export const MISC_PRODUCTS: SeedProduct[] = [
  // marko_juric — outdoor oprema
  {
    sellerKey: 'marko_juric',
    title: 'Deuter Aircontact 65+10 ruksak — terenski, odlično stanje',
    description: 'Deuter Aircontact 65+10 planinarski ruksak za višednevne ture. Aircomfort Vari Flex leđni sustav. Korišten na 4 ture, bez oštećenja. Boja: granite/black.',
    price: 120, currency: 'EUR', country: 'ba', categorySlug: 'sport',
    condition: 'used', listing_type: 'prodaja',
    images: ['https://picsum.photos/seed/deuter-ruck-1/800/600'],
    location: 'Sarajevo', tags: ['deuter', 'ruksak', 'planinarenje', 'trekking', '65l'],
    attributes: {}, views_count: 310, favorites_count: 24, createdDaysAgo: 14, promoted: false,
  },
  {
    sellerKey: 'marko_juric',
    title: 'Salomon X Ultra 4 GTX muške — 43, malo nošene',
    description: 'Salomon X Ultra 4 GTX trekkingice veličine 43. Gore-Tex vodootpornost. Korišćene na par kraćih tura. Odlična grip potplata.',
    price: 95, currency: 'EUR', country: 'ba', categorySlug: 'sport',
    condition: 'like_new', listing_type: 'prodaja',
    images: ['https://picsum.photos/seed/salomon-boots-1/800/600'],
    location: 'Sarajevo', tags: ['salomon', 'planinarke', 'gore-tex', '43', 'trekking'],
    attributes: {}, views_count: 210, favorites_count: 18, createdDaysAgo: 20, promoted: false,
  },
  {
    sellerKey: 'marko_juric',
    title: 'Black Diamond Spot 400 — čeona lampa, odlično',
    description: 'Black Diamond Spot 400 lumen čeona lampa. IP67 vodootpornost. Baterije uključene. Korišćena na nekoliko tura.',
    price: 38, currency: 'EUR', country: 'ba', categorySlug: 'sport',
    condition: 'used', listing_type: 'prodaja',
    images: ['https://picsum.photos/seed/bd-spot-1/800/600'],
    location: 'Sarajevo', tags: ['black diamond', 'čeona lampa', 'planinarenje', 'spot'],
    attributes: {}, views_count: 140, favorites_count: 9, createdDaysAgo: 30, promoted: false,
  },

  // aida_h — dječja odjeća
  {
    sellerKey: 'aida_h',
    title: 'Set dječje odjeće za dječaka 3-4 god — 10 komada',
    description: 'Prodajem set odjeće za dječaka veličine 98-104 (3-4 god). 5 majica, 2 trenerke, 2 hlačice, 1 ljetna jakna. Brendovi: H&M, Zara, Reserved. Sve u odličnom stanju.',
    price: 25, currency: 'EUR', country: 'ba', categorySlug: 'djeca',
    condition: 'used', listing_type: 'prodaja',
    images: ['https://picsum.photos/seed/djeca-odjeca-1/800/600'],
    location: 'Mostar', tags: ['djeca', 'odjeća', 'dječak', '3-4 god', 'set', 'h&m'],
    attributes: {}, views_count: 280, favorites_count: 21, createdDaysAgo: 10, promoted: false,
  },
  {
    sellerKey: 'aida_h',
    title: 'Chicco dječja kolica — Trio 4u1, crna, odlično stanje',
    description: 'Chicco Trio Style kolica 4u1 (krevetić, nosiljka, sjedalica za auto, kolica). Crna boja. Korišćena 1 godinu. Bez oštećenja, sve funkcije rade.',
    price: 180, currency: 'EUR', country: 'ba', categorySlug: 'djeca',
    condition: 'used', listing_type: 'prodaja',
    images: ['https://picsum.photos/seed/chicco-kolica-1/800/600', 'https://picsum.photos/seed/chicco-kolica-2/800/600'],
    location: 'Mostar', tags: ['chicco', 'kolica', 'djeca', '4u1', 'beba'],
    attributes: {}, views_count: 520, favorites_count: 41, createdDaysAgo: 5, promoted: false,
  },

  // pero_v — gaming
  {
    sellerKey: 'pero_v',
    title: 'Xbox Series X — bijeli, 1 TB, 2 kontrolera',
    description: 'Xbox Series X bijele boje (Robot White Limited Edition). 2 Xbox Wireless kontrolera (1 crni, 1 bijeli). Game Pass Ultimate 3 mj. uključen. Odlično stanje, bez ogrebotina.',
    price: 450, currency: 'EUR', country: 'hr', categorySlug: 'videoigre',
    condition: 'like_new', listing_type: 'prodaja',
    images: ['https://picsum.photos/seed/xboxseriesx-1/800/600'],
    location: 'Zagreb', tags: ['xbox', 'series x', 'microsoft', 'gaming', 'konzola'],
    attributes: {}, views_count: 1240, favorites_count: 98, createdDaysAgo: 8, promoted: false,
  },
  {
    sellerKey: 'pero_v',
    title: 'Call of Duty Modern Warfare III — Xbox, nov',
    description: 'Call of Duty Modern Warfare III za Xbox Series X|S i One. Fizička kopija, novo neotvoreno.',
    price: 45, currency: 'EUR', country: 'hr', categorySlug: 'videoigre',
    condition: 'new', listing_type: 'prodaja',
    images: ['https://picsum.photos/seed/codmw3-1/800/600'],
    location: 'Zagreb', tags: ['xbox', 'call of duty', 'igra', 'mw3', 'shooter'],
    attributes: {}, views_count: 180, favorites_count: 12, createdDaysAgo: 22, promoted: false,
  },

  // nermina_k — dom
  {
    sellerKey: 'nermina_k',
    title: 'IKEA KALLAX ormar 4x4 — bijeli, odlično stanje',
    description: 'IKEA KALLAX police 4x4 (147x147cm) u bijeloj boji. Ima sve vijke i upute. Demontirane i složene za transport. Preuzimanje u Tuzli.',
    price: 65, currency: 'EUR', country: 'ba', categorySlug: 'dom',
    condition: 'used', listing_type: 'prodaja',
    images: ['https://picsum.photos/seed/kallax-1/800/600'],
    location: 'Tuzla', tags: ['ikea', 'kallax', 'police', 'ormar', 'bijela'],
    attributes: {}, views_count: 390, favorites_count: 29, createdDaysAgo: 18, promoted: false,
  },
  {
    sellerKey: 'nermina_k',
    title: 'Philips Hue starter set — 4 žarulje + bridge, komplet',
    description: 'Philips Hue White and Color Ambiance E27 starter set. Bridge, 4 žarulje, kabel. Odlično radi. Razlog prodaje: prešla na Home Assistant.',
    price: 120, currency: 'EUR', country: 'ba', categorySlug: 'dom',
    condition: 'used', listing_type: 'prodaja',
    images: ['https://picsum.photos/seed/philips-hue-1/800/600'],
    location: 'Tuzla', tags: ['philips hue', 'pametna rasvjeta', 'smarthome', 'led'],
    attributes: {}, views_count: 440, favorites_count: 35, createdDaysAgo: 25, promoted: false,
  },

  // damir_b — knjige
  {
    sellerKey: 'damir_b',
    title: 'Zbirka pravnih udžbenika — 8 knjiga, Pravni fakultet',
    description: 'Prodajem 8 udžbenika s Pravnog fakulteta: Uvod u pravo, Ustavno pravo, Građansko pravo I i II, Kazneno pravo, Međunarodno pravo, Rimsko pravo, Radno pravo. Svi u odličnom stanju.',
    price: 55, currency: 'EUR', country: 'ba', categorySlug: 'literatura',
    condition: 'used', listing_type: 'prodaja',
    images: ['https://picsum.photos/seed/pravni-knjige-1/800/600'],
    location: 'Banja Luka', tags: ['pravo', 'udžbenik', 'knjige', 'pravni fakultet'],
    attributes: {}, views_count: 160, favorites_count: 11, createdDaysAgo: 15, promoted: false,
  },
  {
    sellerKey: 'damir_b',
    title: 'Sapiens: Kratka povijest čovječanstva — Harari, hr izdanje',
    description: 'Yuval Noah Harari - Sapiens, hrvatsko izdanje, tvrdi uvez. Pročitana jednom. Odlično stanje.',
    price: 12, currency: 'EUR', country: 'ba', categorySlug: 'literatura',
    condition: 'like_new', listing_type: 'prodaja',
    images: ['https://picsum.photos/seed/sapiens-1/800/600'],
    location: 'Banja Luka', tags: ['harari', 'sapiens', 'knjiga', 'filozofija', 'povijest'],
    attributes: {}, views_count: 210, favorites_count: 17, createdDaysAgo: 8, promoted: false,
  },

  // lejla_music — moda
  {
    sellerKey: 'lejla_music',
    title: 'Gucci Marmont torbica replica — zlatna, vintage stil',
    description: 'Visokokvalitetna replika Gucci Marmont torbice u zlatnoj boji. Lanac, GG logotip. Dimenzije 26x15cm. Odlično izrađena, nije original.',
    price: 45, currency: 'EUR', country: 'ba', categorySlug: 'odjeca',
    condition: 'like_new', listing_type: 'prodaja',
    images: ['https://picsum.photos/seed/gucci-rep-1/800/600'],
    location: 'Sarajevo', tags: ['torbica', 'zlatna', 'gucci', 'vintage', 'lanac'],
    attributes: { materijal: 'Eko koža', boja: 'Zlatna', za: 'Žene' },
    views_count: 680, favorites_count: 54, createdDaysAgo: 7, promoted: false,
  },
  {
    sellerKey: 'lejla_music',
    title: 'Massimo Dutti haljina S — bordo, svila, premium',
    description: 'Massimo Dutti svilena haljina veličine S, bordo boja. Midi dužina. Nosila jednom. Idealna za elegantne prigode. Kupljena za 149 EUR.',
    price: 70, currency: 'EUR', country: 'ba', categorySlug: 'odjeca',
    condition: 'like_new', listing_type: 'prodaja',
    images: ['https://picsum.photos/seed/md-haljina-1/800/600'],
    location: 'Sarajevo', tags: ['massimo dutti', 'haljina', 'svila', 'bordo', 's'],
    attributes: {}, views_count: 310, favorites_count: 26, createdDaysAgo: 20, promoted: false,
  },

  // stefan_m — fitnes
  {
    sellerKey: 'stefan_m',
    title: 'Bowflex SelectTech 552 bučice — par, 2-24kg, sklopive',
    description: 'Bowflex SelectTech 552 sklopive bučice. Podešavanje od 2 do 24 kg u koracima od 2,3 kg. Par bučica s postolje. Odlično stanje. Razlog prodaje: kupio barbell set.',
    price: 280, currency: 'EUR', country: 'rs', categorySlug: 'sport',
    condition: 'used', listing_type: 'prodaja',
    images: ['https://picsum.photos/seed/bowflex-1/800/600', 'https://picsum.photos/seed/bowflex-2/800/600'],
    location: 'Beograd', tags: ['bowflex', 'bučice', 'fitnes', 'sklopive', '24kg'],
    attributes: {}, views_count: 840, favorites_count: 67, createdDaysAgo: 6, promoted: false,
  },
  {
    sellerKey: 'stefan_m',
    title: 'Concept2 Model D ergometar — 2020, PM5 monitor, odlično',
    description: 'Concept2 Model D veslaški ergometar s PM5 monitorom. Kupljen 2020., korišćen redovno ali dobro. Sklopiv. Mehanizam gladi kao nov. Razlog: selidba u manji stan.',
    price: 750, currency: 'EUR', country: 'rs', categorySlug: 'sport',
    condition: 'used', listing_type: 'prodaja',
    images: ['https://picsum.photos/seed/concept2-1/800/600'],
    location: 'Beograd', tags: ['concept2', 'ergometar', 'veslanje', 'fitnes', 'pm5'],
    attributes: {}, views_count: 1120, favorites_count: 88, createdDaysAgo: 12, promoted: false,
  },

  // ivana_p — glazba
  {
    sellerKey: 'ivana_p',
    title: 'Yamaha LL16D akustična gitara — solid top, hard case',
    description: 'Yamaha LL16D jumbo akustična gitara s punim smrekovim gornjim soundboardom. Sedefni inlays, gold tuners. Odlična intonacija. Hard case uključen. Prikladna i za studio i live.',
    price: 680, currency: 'EUR', country: 'hr', categorySlug: 'glazba',
    condition: 'like_new', listing_type: 'prodaja',
    images: ['https://picsum.photos/seed/yamaha-gitara-1/800/600'],
    location: 'Split', tags: ['yamaha', 'gitara', 'akustična', 'solid top', 'hard case'],
    attributes: {}, views_count: 480, favorites_count: 38, createdDaysAgo: 16, promoted: false,
  },
  {
    sellerKey: 'ivana_p',
    title: 'Roland FP-30X digitalni klavir — bijeli, stand + pedalbox',
    description: 'Roland FP-30X digitalni klavir u bijeloj boji. 88 tipki s hammer graded akcijom. Superb stereo zvuk. Dolazi s originalnim stalkom KSC-70 i pedalbox KPD-70. Bluetooth MIDI/Audio.',
    price: 580, currency: 'EUR', country: 'hr', categorySlug: 'glazba',
    condition: 'like_new', listing_type: 'prodaja',
    images: ['https://picsum.photos/seed/roland-fp30-1/800/600'],
    location: 'Split', tags: ['roland', 'klavir', 'digitalni', 'fp-30x', 'bijeli'],
    attributes: {}, views_count: 720, favorites_count: 59, createdDaysAgo: 9, promoted: false,
  },

  // edin_s — tehnika
  {
    sellerKey: 'edin_s',
    title: 'Samsung 65" QLED 4K TV — QN90B, 2022, odlično',
    description: 'Samsung 65 inča QLED 4K TV, model QN90B (2022). Neo Quantum procesor, Anti-Reflection ekran, 120Hz. Gaming Mode, FreeSync Premium Pro. Daljinski, stalak, box.',
    price: 890, currency: 'EUR', country: 'ba', categorySlug: 'tehnika',
    condition: 'used', listing_type: 'prodaja',
    images: ['https://picsum.photos/seed/samsung-tv-1/800/600'],
    location: 'Sarajevo', tags: ['samsung', 'televizor', 'qled', '65', '4k', 'smart tv'],
    attributes: {}, views_count: 1480, favorites_count: 112, createdDaysAgo: 4, promoted: false,
  },
  {
    sellerKey: 'edin_s',
    title: 'Bosch perilica rublja WAV28K43 — 9kg, 1400rpm, kao nova',
    description: 'Bosch Serie 8 perilica rublja 9kg, 1400 rpm. EcoSilence Drive motor. iDos automatsko doziranje deterdženta. Home Connect upravljanje mobitelom. Stara samo 1 godinu.',
    price: 520, currency: 'EUR', country: 'ba', categorySlug: 'tehnika',
    condition: 'like_new', listing_type: 'prodaja',
    images: ['https://picsum.photos/seed/bosch-perica-1/800/600'],
    location: 'Sarajevo', tags: ['bosch', 'perilica', 'rublja', '9kg', 'idos', 'smart'],
    attributes: {}, views_count: 670, favorites_count: 51, createdDaysAgo: 11, promoted: false,
  },
  {
    sellerKey: 'edin_s',
    title: 'DJI Mini 4 Pro dron — Fly More Combo, malo letjen',
    description: 'DJI Mini 4 Pro s Fly More Combo paketom. 3 baterije, charging hub, ND filtri. 4K/60fps kamera, OmniDirectional obstacle sensing. Ukupno 6 sati leta. Bez ogrebotina.',
    price: 680, currency: 'EUR', country: 'ba', categorySlug: 'tehnika',
    condition: 'like_new', listing_type: 'prodaja',
    images: ['https://picsum.photos/seed/djimini4-1/800/600'],
    location: 'Sarajevo', tags: ['dji', 'mini 4 pro', 'dron', 'kamera', '4k', 'fly more'],
    attributes: {}, views_count: 1890, favorites_count: 152, createdDaysAgo: 7, promoted: false,
  },

  // maja_d — djeca
  {
    sellerKey: 'maja_d',
    title: 'LEGO City Police Station 60316 — kompletno, s uputom',
    description: 'LEGO City Police Station (Set 60316, 2022). Svi dijelovi prisutni, nije ništa izgubljeno. Uputstvo u odličnom stanju. Figurice sve tu. Savršeno za djecu 6+.',
    price: 55, currency: 'EUR', country: 'ba', categorySlug: 'djeca',
    condition: 'used', listing_type: 'prodaja',
    images: ['https://picsum.photos/seed/lego-police-1/800/600'],
    location: 'Zenica', tags: ['lego', 'city', 'policijska postaja', 'igračke', 'djeca'],
    attributes: {}, views_count: 380, favorites_count: 29, createdDaysAgo: 14, promoted: false,
  },
  {
    sellerKey: 'maja_d',
    title: 'Maxi Cosi Pearl 360 autosjedalica — 0-18kg, siva',
    description: 'Maxi Cosi Pearl 360 Pro autosjedalica za djecu od 0 do 18 kg. Rotacija 360°, izolob zaštita. Uz sjedalicu i baza FamilyFix 360 za lagan montaž. Korišćena 2 god. Sivi tapecirani materijal.',
    price: 180, currency: 'EUR', country: 'ba', categorySlug: 'djeca',
    condition: 'used', listing_type: 'prodaja',
    images: ['https://picsum.photos/seed/maxicosi-1/800/600'],
    location: 'Zenica', tags: ['maxi cosi', 'autosjedalica', 'beba', '360', 'isofix'],
    attributes: {}, views_count: 560, favorites_count: 44, createdDaysAgo: 8, promoted: false,
  },

  // zlatko_r — auto dijelovi
  {
    sellerKey: 'zlatko_r',
    title: 'Set zimskih guma 205/55 R16 — Michelin, 4 kom, malo nošene',
    description: 'Michelin Alpin 5 zimske gume dimenzije 205/55 R16. Dubina šare prosječno 7mm (nove su 7.5mm). Svega jedna sezona. Bez popravki ili fleki.',
    price: 220, currency: 'EUR', country: 'ba', categorySlug: 'dij-auto-felge',
    condition: 'used', listing_type: 'prodaja',
    images: ['https://picsum.photos/seed/michelingume-1/800/600'],
    location: 'Sarajevo', tags: ['michelin', 'zimske gume', '205/55 r16', 'alpin 5'],
    attributes: {}, views_count: 510, favorites_count: 38, createdDaysAgo: 20, promoted: false,
  },
  {
    sellerKey: 'zlatko_r',
    title: 'Bosch akumulatorska bušilica GSR 18V-50 — 2 baterije, kofer',
    description: 'Bosch Professional GSR 18V-50 bušilica-odvijač. 2 baterije 2.0 Ah, punjač, Pro kofer. Odlično stanje, korišćena za hobbyje. Brushless motor.',
    price: 140, currency: 'EUR', country: 'ba', categorySlug: 'strojevi',
    condition: 'used', listing_type: 'prodaja',
    images: ['https://picsum.photos/seed/bosch-drill-1/800/600'],
    location: 'Sarajevo', tags: ['bosch', 'bušilica', '18v', 'akumulatorska', 'professional'],
    attributes: {}, views_count: 340, favorites_count: 25, createdDaysAgo: 16, promoted: false,
  },

  // selma_a — odjeća
  {
    sellerKey: 'selma_a',
    title: 'Pull&Bear oversized hoodie XS/S — crni, novi',
    description: 'Pull&Bear oversized hoodie u crnoj boji. Nikad nošen, s etiketom. Debelji pamučni materijal, savršen za jesen.',
    price: 18, currency: 'EUR', country: 'ba', categorySlug: 'odjeca',
    condition: 'new', listing_type: 'prodaja',
    images: ['https://picsum.photos/seed/pullbear-hoodie-1/800/600'],
    location: 'Mostar', tags: ['pull&bear', 'hoodie', 'crni', 'oversized', 'xs'],
    attributes: {}, views_count: 180, favorites_count: 14, createdDaysAgo: 12, promoted: false,
  },
  {
    sellerKey: 'selma_a',
    title: 'Bershka zimska jakna M — khaki, teddy obloga, topla',
    description: 'Bershka zimska jakna veličine M, khaki boja s teddy oblogom. Nošena jednu sezonu, odlično stanje.',
    price: 25, currency: 'EUR', country: 'ba', categorySlug: 'odjeca',
    condition: 'used', listing_type: 'prodaja',
    images: ['https://picsum.photos/seed/bershka-jakna-1/800/600'],
    location: 'Mostar', tags: ['bershka', 'jakna', 'zimska', 'khaki', 'm'],
    attributes: {}, views_count: 220, favorites_count: 16, createdDaysAgo: 25, promoted: false,
  },

  // filip_n — gaming
  {
    sellerKey: 'filip_n',
    title: 'Xbox Elite Controller Series 2 — crni, malo korišten',
    description: 'Xbox Elite Wireless Controller Series 2 u crnoj boji. Podešavajuće paddles, zamjenjivi thumbsticks i d-pad. Punjivi baterija. Malo korišten.',
    price: 110, currency: 'EUR', country: 'hr', categorySlug: 'videoigre',
    condition: 'like_new', listing_type: 'prodaja',
    images: ['https://picsum.photos/seed/xbox-elite-1/800/600'],
    location: 'Zagreb', tags: ['xbox', 'elite', 'controller', 'series 2', 'gamepad'],
    attributes: {}, views_count: 640, favorites_count: 52, createdDaysAgo: 10, promoted: false,
  },

  // jasmina_b — dom
  {
    sellerKey: 'jasmina_b',
    title: 'Bolia tepih — 200x300cm, vuna, geometrijski uzorak',
    description: 'Bolia dizajnerski tepih od 100% vune, 200x300cm. Geometrijski crno-bijeli uzorak. Odlično stanje, čišćen profesionalno. Kupljen za 650 EUR.',
    price: 280, currency: 'EUR', country: 'ba', categorySlug: 'dom',
    condition: 'used', listing_type: 'prodaja',
    images: ['https://picsum.photos/seed/bolia-tepih-1/800/600', 'https://picsum.photos/seed/bolia-tepih-2/800/600'],
    location: 'Banja Luka', tags: ['tepih', 'vuna', 'bolia', 'dizajnerski', '200x300'],
    attributes: {}, views_count: 390, favorites_count: 31, createdDaysAgo: 22, promoted: false,
  },

  // armin_h — ski oprema
  {
    sellerKey: 'armin_h',
    title: 'Rossignol Experience 86 TI skije 176cm — 2023, malo nošene',
    description: 'Rossignol Experience 86 TI skije dužine 176cm, sezona 2022/23. Korišćene jednu sezonu. Wax i brušenje napravljeno. Bez ogrebotina na baznoj ploči.',
    price: 290, currency: 'EUR', country: 'ba', categorySlug: 'sport',
    condition: 'used', listing_type: 'prodaja',
    images: ['https://picsum.photos/seed/rossignol-ski-1/800/600'],
    location: 'Sarajevo', tags: ['rossignol', 'skije', '176cm', 'all mountain', 'ski'],
    attributes: {}, views_count: 430, favorites_count: 33, createdDaysAgo: 15, promoted: false,
  },
  {
    sellerKey: 'armin_h',
    title: 'Salomon QST Pro 110 ski cipele — 28.5 (44), 2022',
    description: 'Salomon QST Pro 110 cipele za skijanje, veličina 28.5 (EU44). All-mountain ski cipele s dobrom fleksijom. Jedna sezona. Myfit liner.',
    price: 180, currency: 'EUR', country: 'ba', categorySlug: 'sport',
    condition: 'used', listing_type: 'prodaja',
    images: ['https://picsum.photos/seed/skiboots-1/800/600'],
    location: 'Sarajevo', tags: ['salomon', 'ski cipele', '44', 'all mountain', 'skijanje'],
    attributes: {}, views_count: 310, favorites_count: 25, createdDaysAgo: 20, promoted: false,
  },

  // tina_j — torbice
  {
    sellerKey: 'tina_j',
    title: 'Coach Tabitha torbica — crna koža, smeđi detalji, original',
    description: 'Coach Tabitha crossbody torbica od prave kože. Crna s brown horse i carriage logotipom. Original s certifikatom autentičnosti. Kupljena u Coach boutique.',
    price: 190, currency: 'EUR', country: 'hr', categorySlug: 'odjeca',
    condition: 'like_new', listing_type: 'prodaja',
    images: ['https://picsum.photos/seed/coach-torbica-1/800/600'],
    location: 'Split', tags: ['coach', 'torbica', 'crossbody', 'koža', 'original'],
    attributes: { materijal: 'Koža', brand: 'Coach', boja: 'Crna', za: 'Žene' },
    views_count: 710, favorites_count: 58, createdDaysAgo: 8, promoted: false,
  },

  // milos_d — fotografija
  {
    sellerKey: 'milos_d',
    title: 'Canon EOS R6 Mark II + RF 24-105mm f/4 — kit, odlično',
    description: 'Canon EOS R6 Mark II fullframe mirrorless kamera s RF 24-105mm f/4L IS USM objektivom. Kit torba, 2 baterije LP-E6NH, punjač, originalna vrpca. Ukupno oko 15.000 okidanja.',
    price: 2800, currency: 'EUR', country: 'rs', categorySlug: 'tehnika',
    condition: 'used', listing_type: 'prodaja',
    images: ['https://picsum.photos/seed/canonr6-1/800/600', 'https://picsum.photos/seed/canonr6-2/800/600'],
    location: 'Beograd', tags: ['canon', 'eos r6', 'mirrorless', 'kamera', 'rf 24-105'],
    attributes: {}, views_count: 2140, favorites_count: 172, createdDaysAgo: 5, promoted: false,
  },

  // sabina_k — knjige
  {
    sellerKey: 'sabina_k',
    title: 'Set dječjih slikovnica — 20 komada, 2-5 god',
    description: 'Set od 20 slikovnica za djecu 2-5 godina. Uključuje: Peppa Pig (5 kom), Disney (6 kom), domaće autorske (9 kom). Sve u odličnom stanju, nema nacrta ni istrgnutih stranica.',
    price: 30, currency: 'EUR', country: 'ba', categorySlug: 'literatura',
    condition: 'used', listing_type: 'prodaja',
    images: ['https://picsum.photos/seed/djecje-knjige-1/800/600'],
    location: 'Tuzla', tags: ['slikovnice', 'djeca', 'knjige', 'peppa', 'disney'],
    attributes: {}, views_count: 250, favorites_count: 19, createdDaysAgo: 12, promoted: false,
  },

  // goran_p — audio
  {
    sellerKey: 'goran_p',
    title: 'Sonos Era 300 par — prostorni zvuk, crni, malo korišten',
    description: 'Par Sonos Era 300 Dolby Atmos zvučnika. Crna boja. Postavljeni kao surround par, korišćeni 4 mj. u odličnom stanju. Trueplay kalibracija.',
    price: 780, currency: 'EUR', country: 'ba', categorySlug: 'tehnika',
    condition: 'like_new', listing_type: 'prodaja',
    images: ['https://picsum.photos/seed/sonos-era-1/800/600'],
    location: 'Banja Luka', tags: ['sonos', 'era 300', 'zvučnik', 'dolby atmos', 'bežični'],
    attributes: {}, views_count: 870, favorites_count: 69, createdDaysAgo: 9, promoted: false,
  },

  // emina_m — medicinska literatura
  {
    sellerKey: 'emina_m',
    title: 'Harrison\'s Principles of Internal Medicine — 21. izdanje, en',
    description: 'Harrison\'s Principles of Internal Medicine, 21. izdanje (2022), engleski. Dvosveščanik u kutiji. Malo korišćen, bez podvlačenja. Esencijalni referentni udžbenik za doktore.',
    price: 85, currency: 'EUR', country: 'ba', categorySlug: 'literatura',
    condition: 'like_new', listing_type: 'prodaja',
    images: ['https://picsum.photos/seed/harrison-1/800/600'],
    location: 'Sarajevo', tags: ['medicina', 'harrison', 'udžbenik', 'interna medicina', 'engleski'],
    attributes: {}, views_count: 190, favorites_count: 14, createdDaysAgo: 18, promoted: false,
  },

  // luka_s — skateboarding
  {
    sellerKey: 'luka_s',
    title: 'Element skate deck 8.25" — Timber, malo nošen',
    description: 'Element Timber Series maple skateboard deck 8.25 inča. Nošen jednu sezonu, malo trošena ruba. Grip tape uključen. Odlično za pool/park.',
    price: 45, currency: 'EUR', country: 'hr', categorySlug: 'sport',
    condition: 'used', listing_type: 'prodaja',
    images: ['https://picsum.photos/seed/element-deck-1/800/600'],
    location: 'Zagreb', tags: ['element', 'skateboard', 'deck', '8.25', 'timber'],
    attributes: {}, views_count: 160, favorites_count: 12, createdDaysAgo: 22, promoted: false,
  },
  {
    sellerKey: 'luka_s',
    title: 'Nike SB Dunk Low Pro — bijele/zelene, 42, malo nošene',
    description: 'Nike SB Dunk Low Pro tenisice za skateboarding, veličina 42. Bijelo-zelena kombinacija boja. Nošene nekoliko puta, bez majority oštećenja.',
    price: 90, currency: 'EUR', country: 'hr', categorySlug: 'sport',
    condition: 'like_new', listing_type: 'prodaja',
    images: ['https://picsum.photos/seed/nikesbdunk-1/800/600'],
    location: 'Zagreb', tags: ['nike', 'sb dunk', 'skateboarding', 'tenisice', '42'],
    attributes: {}, views_count: 480, favorites_count: 38, createdDaysAgo: 14, promoted: false,
  },

  // nina_v — nakit
  {
    sellerKey: 'nina_v',
    title: 'Ručno rađena ogrlica — srebro 925, majsko lišće, unikatno',
    description: 'Unikatna ogrlica od srebra 925/1000, ručno izrađena. Privjesak u obliku majskog lišća, promjer 22mm. Lančić dužine 45cm, karabinska kopča. S kutijom i certifikatom.',
    price: 55, currency: 'EUR', country: 'rs', categorySlug: 'odjeca',
    condition: 'new', listing_type: 'prodaja',
    images: ['https://picsum.photos/seed/silver-ogrlica-1/800/600'],
    location: 'Novi Sad', tags: ['ogrlica', 'srebro', 'ručni rad', 'nakit', 'unikatno'],
    attributes: { materijal: 'Srebro', boja: 'Srebrna', za: 'Žene' },
    views_count: 320, favorites_count: 26, createdDaysAgo: 10, promoted: false,
  },
  {
    sellerKey: 'nina_v',
    title: 'Set naušnica — srebro 925, 5 pari, razni modeli',
    description: 'Set od 5 pari ručno rađenih naušnica od srebra 925. Različiti modeli: karike, klinovi, dangla. Paket po specijalnoj cijeni. Sve nove s certifikatom.',
    price: 80, currency: 'EUR', country: 'rs', categorySlug: 'odjeca',
    condition: 'new', listing_type: 'prodaja',
    images: ['https://picsum.photos/seed/silver-nausnice-1/800/600'],
    location: 'Novi Sad', tags: ['naušnice', 'srebro', 'ručni rad', 'set', 'nakit'],
    attributes: { materijal: 'Srebro', boja: 'Srebrna', za: 'Žene' },
    views_count: 410, favorites_count: 33, createdDaysAgo: 15, promoted: false,
  },

  // haris_t — kućanski aparati
  {
    sellerKey: 'haris_t',
    title: 'Nespresso Vertuo Next — crni, malo korišten, kapsule uključene',
    description: 'Nespresso Vertuo Next aparat za kavu u crnoj boji. Barcode scanning tehnologija. Korišćen 3 mj. U paketu 30 kapsula raznih okusa.',
    price: 75, currency: 'EUR', country: 'ba', categorySlug: 'tehnika',
    condition: 'like_new', listing_type: 'prodaja',
    images: ['https://picsum.photos/seed/nespresso-1/800/600'],
    location: 'Sarajevo', tags: ['nespresso', 'vertuo', 'kava', 'aparat', 'crni'],
    attributes: {}, views_count: 490, favorites_count: 39, createdDaysAgo: 12, promoted: false,
  },
  {
    sellerKey: 'haris_t',
    title: 'Philips Airfryer XL 6.2L — crni, malo korišten',
    description: 'Philips Airfryer XXL 6.2L u crnoj boji s Rapid Air tehnologijom. Kapacitet 1.4kg. Malo korišten. Idealan za zdravu pripremu hrane.',
    price: 110, currency: 'EUR', country: 'ba', categorySlug: 'tehnika',
    condition: 'like_new', listing_type: 'prodaja',
    images: ['https://picsum.photos/seed/airfryer-1/800/600'],
    location: 'Sarajevo', tags: ['philips', 'airfryer', 'kuhanje', 'zdravo', '6.2l'],
    attributes: {}, views_count: 620, favorites_count: 48, createdDaysAgo: 8, promoted: false,
  },

  // kristina_l — dom dekor
  {
    sellerKey: 'kristina_l',
    title: 'Scandi tepih vuna 140x200cm — bijelo-sivi, odlično stanje',
    description: 'Skandinavski dizajnerski tepih od mješavine vune i pamuka. Bijelo-sivi uzorak, dimenzije 140x200cm. Jednom opran profesionalno. Savršen za scandi ili minimalistički interior.',
    price: 95, currency: 'EUR', country: 'hr', categorySlug: 'dom',
    condition: 'used', listing_type: 'prodaja',
    images: ['https://picsum.photos/seed/scandi-tepih-1/800/600'],
    location: 'Zagreb', tags: ['tepih', 'vuna', 'scandi', '140x200', 'bijeli'],
    attributes: {}, views_count: 280, favorites_count: 22, createdDaysAgo: 20, promoted: false,
  },

  // ismar_o — gume
  {
    sellerKey: 'ismar_o',
    title: 'Set ljetnih guma 225/45 R17 — Pirelli P Zero, 4 kom',
    description: 'Pirelli P Zero ljetne gume dimenzija 225/45 R17. Dubina šare prosječno 6mm. Dvije sezone. Bez krpa ili popravaka. Preuzimanje u Sarajevu.',
    price: 200, currency: 'EUR', country: 'ba', categorySlug: 'dij-auto-felge',
    condition: 'used', listing_type: 'prodaja',
    images: ['https://picsum.photos/seed/pirelli-gume-1/800/600'],
    location: 'Sarajevo', tags: ['pirelli', 'ljetne gume', '225/45 r17', 'p zero'],
    attributes: {}, views_count: 470, favorites_count: 36, createdDaysAgo: 14, promoted: false,
  },

  // ana_b — dječja odjeća
  {
    sellerKey: 'ana_b',
    title: 'H&M zimska jakna za djevojčice 116 — roza, topla, kao nova',
    description: 'H&M zimska jakna za djevojčice veličine 116 (5-6 god) u rozo boji. Topla obloga, kapuljača, reflektirajuće trake. Nošena jednu zimu.',
    price: 15, currency: 'EUR', country: 'hr', categorySlug: 'djeca',
    condition: 'used', listing_type: 'prodaja',
    images: ['https://picsum.photos/seed/hm-djevojcica-jakna-1/800/600'],
    location: 'Osijek', tags: ['hm', 'jakna', 'djevojčice', '116', 'roza', 'zimska'],
    attributes: {}, views_count: 200, favorites_count: 15, createdDaysAgo: 18, promoted: false,
  },
  {
    sellerKey: 'ana_b',
    title: 'Chicco dječja cipele — 22, bijele, za prve korake',
    description: 'Chicco First Steps cipele veličine 22 za prve korake. Bijela boja, fleksibilan đon. Korišćene malo, dijete brzo naraslo.',
    price: 12, currency: 'EUR', country: 'hr', categorySlug: 'djeca',
    condition: 'like_new', listing_type: 'prodaja',
    images: ['https://picsum.photos/seed/chicco-cipele-1/800/600'],
    location: 'Osijek', tags: ['chicco', 'cipele', 'djeca', '22', 'prvi koraci'],
    attributes: {}, views_count: 160, favorites_count: 11, createdDaysAgo: 25, promoted: false,
  },
];
