import type { SeedProduct } from './types.js';

// 8 tech listings for TechZone (pro account)
export const TECH_PRODUCTS: SeedProduct[] = [
  {
    sellerKey: 'techzone_bh',
    title: 'iPhone 15 Pro Max 256GB — Natural Titanium, 100% baterija',
    description: 'iPhone 15 Pro Max u boji Natural Titanium. Kupljen u ovlaštenom Apple prodavaonici u Beču. Fabrička kutija, punjač, kabel uključeni. Ekran bez ogrebotina. Zdravlje baterije 100% (provjeri u Postavkama). Face ID radi savršeno. Dostava brzom poštom ili preuzimanje u Banjoj Luci.',
    price: 1090,
    currency: 'EUR',
    country: 'ba',
    categorySlug: 'mobiteli',
    condition: 'like_new',
    listing_type: 'prodaja',
    images: [
      'https://picsum.photos/seed/iphone15pm-1/800/600',
      'https://picsum.photos/seed/iphone15pm-2/800/600',
    ],
    location: 'Banja Luka',
    tags: ['iphone', '15', 'pro max', 'apple', 'titanium', '256gb'],
    attributes: {
      memorija: '256GB',
      ram: '8GB',
      boja: 'Siva',
      zdravljeBaterije: '100%',
      stanjeEkrana: 'Savršeno',
      dualSim: false,
      esim: true,
      punjac: true,
      slusalice: false,
      vodootporan: true,
      fabrickaKutija: true,
      ostecen: false,
    },
    views_count: 1340,
    favorites_count: 102,
    createdDaysAgo: 4,
    promoted: true,
  },
  {
    sellerKey: 'techzone_bh',
    title: 'Samsung Galaxy S24 Ultra 512GB — Titanium Black, garancija do 02/2026',
    description: 'Samsung Galaxy S24 Ultra u crnoj titanijum boji, 512GB memorije. S Pen uključen. Garancija vrijedi do 02/2026. Korišten 3 mjeseca, u savršenom stanju. Zaštitna folija na ekranu i originalnom maskom. Dostupan odmah.',
    price: 1150,
    currency: 'EUR',
    country: 'ba',
    categorySlug: 'mobiteli',
    condition: 'like_new',
    listing_type: 'prodaja',
    images: [
      'https://picsum.photos/seed/s24ultra-1/800/600',
      'https://picsum.photos/seed/s24ultra-2/800/600',
    ],
    location: 'Banja Luka',
    tags: ['samsung', 'galaxy', 's24', 'ultra', '512gb', 's pen'],
    attributes: {
      memorija: '512GB',
      ram: '12GB',
      boja: 'Crna',
      zdravljeBaterije: '95-99%',
      stanjeEkrana: 'Savršeno',
      dualSim: true,
      esim: true,
      punjac: true,
      slusalice: false,
      vodootporan: true,
      fabrickaKutija: true,
      ostecen: false,
    },
    views_count: 980,
    favorites_count: 74,
    createdDaysAgo: 9,
    promoted: false,
  },
  {
    sellerKey: 'techzone_bh',
    title: 'MacBook Pro 14" M3 Pro — Space Black, 18GB RAM, 512GB SSD',
    description: 'MacBook Pro 14 inča s M3 Pro čipom u Space Black boji. 18GB unificirane memorije, 512GB SSD. Koristio sam 6 tjedana za testiranje, prešao na desktop Mac Studio. Baterija drži 17+ sati na jednom punjenju. MagSafe, dva Thunderbolt 4, HDMI, SD čitač. Fabrička kutija, magsafe punjač uključen. Garancija Apple do 04/2026.',
    price: 2290,
    currency: 'EUR',
    country: 'ba',
    categorySlug: 'racunala',
    condition: 'like_new',
    listing_type: 'prodaja',
    images: [
      'https://picsum.photos/seed/macbookm3-1/800/600',
      'https://picsum.photos/seed/macbookm3-2/800/600',
    ],
    location: 'Banja Luka',
    tags: ['macbook', 'pro', 'm3', 'apple', 'laptop', 'space black', '14 inča'],
    attributes: {},
    views_count: 2180,
    favorites_count: 167,
    createdDaysAgo: 7,
    promoted: true,
  },
  {
    sellerKey: 'techzone_bh',
    title: 'Xiaomi Redmi Note 13 Pro+ 256GB — Midnight Black, dual SIM',
    description: 'Xiaomi Redmi Note 13 Pro+ 5G, 256GB interne memorije i 12GB RAM-a. Kupljen nov, malo korišten. Kamera 200MP. Brzo punjenje 120W. Dual SIM. Idealan za korisnike koji žele vrhunske performanse po pristupačnoj cijeni.',
    price: 340,
    currency: 'EUR',
    country: 'ba',
    categorySlug: 'mobiteli',
    condition: 'like_new',
    listing_type: 'prodaja',
    images: [
      'https://picsum.photos/seed/redminote13-1/800/600',
      'https://picsum.photos/seed/redminote13-2/800/600',
    ],
    location: 'Banja Luka',
    tags: ['xiaomi', 'redmi', 'note 13', 'pro+', '5g', '256gb', 'dual sim'],
    attributes: {
      memorija: '256GB',
      ram: '12GB',
      boja: 'Crna',
      zdravljeBaterije: '100%',
      stanjeEkrana: 'Savršeno',
      dualSim: true,
      esim: false,
      punjac: true,
      slusalice: false,
      vodootporan: false,
      fabrickaKutija: true,
      ostecen: false,
    },
    views_count: 560,
    favorites_count: 38,
    createdDaysAgo: 15,
    promoted: false,
  },
  {
    sellerKey: 'techzone_bh',
    title: 'Apple iPad Pro 12.9" M2 — 256GB WiFi, Space Gray, bez ogrebotina',
    description: 'iPad Pro 12.9 inča s M2 čipom. 256GB WiFi verzija. Ekran Liquid Retina XDR bez ogrebotina ili napuknuća. Smart Folio maskom, Apple Pencil 2. generacije (punjač i vrh uključeni). Garancija do 11/2025.',
    price: 980,
    currency: 'EUR',
    country: 'ba',
    categorySlug: 'mobiteli',
    condition: 'like_new',
    listing_type: 'prodaja',
    images: [
      'https://picsum.photos/seed/ipadpro-1/800/600',
      'https://picsum.photos/seed/ipadpro-2/800/600',
    ],
    location: 'Banja Luka',
    tags: ['ipad', 'pro', 'apple', '12.9', 'm2', 'tablet', 'pencil'],
    attributes: {
      memorija: '256GB',
      dijagonala: '12.9"',
      boja: 'Siva',
      stanjeEkrana: 'Savršeno',
      punjac: true,
      fabrickaKutija: true,
    },
    views_count: 1620,
    favorites_count: 123,
    createdDaysAgo: 6,
    promoted: false,
  },
  {
    sellerKey: 'techzone_bh',
    title: 'Sony PlayStation 5 Slim — disc edition, 2 kontrolera, 4 igre',
    description: 'PS5 Slim (disc edition) u bijeloj boji. Uz konzolu dolaze 2 DualSense kontrolera, 4 igre (FIFA 25, Spider-Man 2, Gran Turismo 7, Mortal Kombat 1). HDMI 2.1 kabl. Sve u originalnom pakovanju. Bez ogrebotina.',
    price: 580,
    currency: 'EUR',
    country: 'ba',
    categorySlug: 'videoigre',
    condition: 'like_new',
    listing_type: 'prodaja',
    images: [
      'https://picsum.photos/seed/ps5slim-1/800/600',
      'https://picsum.photos/seed/ps5slim-2/800/600',
    ],
    location: 'Banja Luka',
    tags: ['playstation', 'ps5', 'slim', 'sony', 'gaming', 'konzola'],
    attributes: {},
    views_count: 2890,
    favorites_count: 234,
    createdDaysAgo: 3,
    promoted: true,
  },
  {
    sellerKey: 'techzone_bh',
    title: 'Lenovo ThinkPad X1 Carbon Gen 11 — i7-1365U, 32GB, 1TB',
    description: 'Lenovo ThinkPad X1 Carbon 11. generacije. Intel Core i7-1365U, 32GB LPDDR5, 1TB NVMe SSD. 14" WUXGA IPS ekran, 16 sati autonomije. Fingerprint senzor, IR kamera za Windows Hello. Savršen poslovni laptop. Garancija do 03/2026.',
    price: 1480,
    currency: 'EUR',
    country: 'ba',
    categorySlug: 'racunala',
    condition: 'like_new',
    listing_type: 'prodaja',
    images: [
      'https://picsum.photos/seed/thinkpadx1-1/800/600',
      'https://picsum.photos/seed/thinkpadx1-2/800/600',
    ],
    location: 'Banja Luka',
    tags: ['lenovo', 'thinkpad', 'x1 carbon', 'laptop', 'i7', '32gb', 'poslovni'],
    attributes: {},
    views_count: 890,
    favorites_count: 67,
    createdDaysAgo: 12,
    promoted: false,
  },
  {
    sellerKey: 'techzone_bh',
    title: 'Apple Watch Ultra 2 — Titanium, Alpine Loop, baterija 70%',
    description: 'Apple Watch Ultra 2 u titanijum kućištu, 49mm. Alpine Loop narukvica L veličine (narandžasta). Zdravlje baterije 70% nakon 14 mjeseci korištenja. Ekran bez ogrebotina. Vodootporan do 100 metara. Sve originalno pakovanje.',
    price: 620,
    currency: 'EUR',
    country: 'ba',
    categorySlug: 'mobiteli',
    condition: 'used',
    listing_type: 'prodaja',
    images: [
      'https://picsum.photos/seed/applewatchultra-1/800/600',
      'https://picsum.photos/seed/applewatchultra-2/800/600',
    ],
    location: 'Banja Luka',
    tags: ['apple watch', 'ultra 2', 'titanium', 'smartwatch', 'alpine loop'],
    attributes: {
      boja: 'Srebrna',
      kompatibilnost: 'iOS',
      vodootporan: true,
      fabrickaKutija: true,
    },
    views_count: 1080,
    favorites_count: 88,
    createdDaysAgo: 20,
    promoted: false,
  },
];
