import type { SeedProduct } from './types.js';

// 10 fashion listings for Fashion Haus (pro account)
export const FASHION_PRODUCTS: SeedProduct[] = [
  {
    sellerKey: 'fashion_haus',
    title: 'Tommy Hilfiger zimska jakna M — navy blue, nova s etiketom',
    description: 'Tommy Hilfiger originalna zimska jakna veličine M za muškarce. Navy blue boja, vodootporni materijal, topla obloga. Nova s originalnom etiketom i kutijom. Kupljena u Beču za 249 EUR. Prodajem jer sam dobio istu na poklon.',
    price: 149,
    currency: 'EUR',
    country: 'ba',
    categorySlug: 'odjeca',
    condition: 'new',
    listing_type: 'prodaja',
    images: [
      'https://picsum.photos/seed/tommy-jakna-1/800/600',
      'https://picsum.photos/seed/tommy-jakna-2/800/600',
    ],
    location: 'Mostar',
    tags: ['tommy hilfiger', 'jakna', 'zimska', 'muška', 'nova', 'navy'],
    attributes: {},
    views_count: 420,
    favorites_count: 34,
    createdDaysAgo: 8,
    promoted: false,
  },
  {
    sellerKey: 'fashion_haus',
    title: 'Zara ženska haljina S — floral print, ljetna, kao nova',
    description: 'Zara haljina veličine S, floral print, midi dužina. Nosila sam je samo jednom na svadbi. Stanje kao novo, bez ikakvih oštećenja. Idealna za ljetne prilike, vjenčanja i evente. Kupljena u travnju 2024.',
    price: 35,
    currency: 'EUR',
    country: 'ba',
    categorySlug: 'odjeca',
    condition: 'like_new',
    listing_type: 'prodaja',
    images: [
      'https://picsum.photos/seed/zara-haljina-1/800/600',
      'https://picsum.photos/seed/zara-haljina-2/800/600',
    ],
    location: 'Mostar',
    tags: ['zara', 'haljina', 'ženska', 'ljetna', 'floral', 's'],
    attributes: {},
    views_count: 310,
    favorites_count: 28,
    createdDaysAgo: 15,
    promoted: false,
  },
  {
    sellerKey: 'fashion_haus',
    title: 'Nike Air Max 90 — bijele, 42, original, malo nošene',
    description: 'Nike Air Max 90 tenisice broj 42. Originalnog su porijekla, kupljene u Nike Factoryju u Beogradu. Nošene su nekoliko puta, u odličnom stanju. Bijela boja s crnim detaljima. Uključen originalni karton.',
    price: 80,
    currency: 'EUR',
    country: 'ba',
    categorySlug: 'odjeca',
    condition: 'like_new',
    listing_type: 'prodaja',
    images: [
      'https://picsum.photos/seed/nikeam90-1/800/600',
      'https://picsum.photos/seed/nikeam90-2/800/600',
    ],
    location: 'Mostar',
    tags: ['nike', 'air max', '90', 'tenisice', 'muške', 'bijele', '42'],
    attributes: {},
    views_count: 680,
    favorites_count: 52,
    createdDaysAgo: 12,
    promoted: true,
  },
  {
    sellerKey: 'fashion_haus',
    title: 'Mango trench kaput ženska L — camel, jesen, kao nov',
    description: 'Mango klasični trench kaput veličine L u camel boji. Jesenska kolekcija 2024. Nosila sam ga jednom na kratko, kupila sam istu stvar u crnoj pa ne trebam camel. Kupljen za 120 EUR.',
    price: 65,
    currency: 'EUR',
    country: 'ba',
    categorySlug: 'odjeca',
    condition: 'like_new',
    listing_type: 'prodaja',
    images: [
      'https://picsum.photos/seed/mango-kaput-1/800/600',
      'https://picsum.photos/seed/mango-kaput-2/800/600',
    ],
    location: 'Mostar',
    tags: ['mango', 'kaput', 'trench', 'ženska', 'camel', 'jesen', 'l'],
    attributes: {},
    views_count: 280,
    favorites_count: 22,
    createdDaysAgo: 20,
    promoted: false,
  },
  {
    sellerKey: 'fashion_haus',
    title: 'H&M muška zimska jakna XL — crna, puffer, topla',
    description: 'H&M muška zimska puffer jakna veličine XL. Crna boja, topla obloga, s kapuljačom. Dosta topla za zimu do -15°C. Korišćena jednu sezonu, bez ikakvih oštećenja. Odlična cijena za H&M kvalitetu.',
    price: 28,
    currency: 'EUR',
    country: 'ba',
    categorySlug: 'odjeca',
    condition: 'used',
    listing_type: 'prodaja',
    images: [
      'https://picsum.photos/seed/hm-jakna-1/800/600',
    ],
    location: 'Mostar',
    tags: ['hm', 'jakna', 'puffer', 'muška', 'crna', 'zimska', 'xl'],
    attributes: {},
    views_count: 190,
    favorites_count: 14,
    createdDaysAgo: 30,
    promoted: false,
  },
  {
    sellerKey: 'fashion_haus',
    title: 'Michael Kors kožna torbica — smeđa, srednja, original',
    description: 'Michael Kors original torbica od prave kože, smeđa boja. Srednja veličina, idealna za svakodnevnu upotrebu. Unutra dva pretinca, džep za mobitel. Bez ogrebotina ili oštećenja. S originalnim kutijom i vrećicom.',
    price: 145,
    currency: 'EUR',
    country: 'ba',
    categorySlug: 'odjeca',
    condition: 'like_new',
    listing_type: 'prodaja',
    images: [
      'https://picsum.photos/seed/mk-torbica-1/800/600',
      'https://picsum.photos/seed/mk-torbica-2/800/600',
    ],
    location: 'Mostar',
    tags: ['michael kors', 'torbica', 'koža', 'smeđa', 'original', 'ženska'],
    attributes: {
      materijal: 'Koža',
      brand: 'Michael Kors',
      boja: 'Smeđa',
      za: 'Žene',
    },
    views_count: 860,
    favorites_count: 71,
    createdDaysAgo: 5,
    promoted: true,
  },
  {
    sellerKey: 'fashion_haus',
    title: 'Adidas Ultraboost 22 — siva, 41, original, trčanje',
    description: 'Adidas Ultraboost 22 tenisice za trčanje, veličina EU 41 (UK 7.5). Boost tehnologija, Primeknit gornjište. Kupljene u Adidas prodavaonici u Sarajevu za 180 EUR. Korišćene za trčanje oko 3 puta, u izvrsnom stanju. Sva originalna dokumentacija.',
    price: 90,
    currency: 'EUR',
    country: 'ba',
    categorySlug: 'odjeca',
    condition: 'like_new',
    listing_type: 'prodaja',
    images: [
      'https://picsum.photos/seed/ultraboost-1/800/600',
      'https://picsum.photos/seed/ultraboost-2/800/600',
    ],
    location: 'Mostar',
    tags: ['adidas', 'ultraboost', 'trčanje', 'tenisice', 'siva', '41', 'boost'],
    attributes: {},
    views_count: 540,
    favorites_count: 43,
    createdDaysAgo: 18,
    promoted: false,
  },
  {
    sellerKey: 'fashion_haus',
    title: 'Ralph Lauren polo majica XL — navy, original, nova s etiketom',
    description: 'Ralph Lauren Polo majica veličine XL u navy plavoj boji. Nova s originalnom etiketom, nikad nošena. Klasični polo kroj, pamuk 100%. Kupljena u duty-free zoni.',
    price: 65,
    currency: 'EUR',
    country: 'ba',
    categorySlug: 'odjeca',
    condition: 'new',
    listing_type: 'prodaja',
    images: [
      'https://picsum.photos/seed/ralph-polo-1/800/600',
    ],
    location: 'Mostar',
    tags: ['ralph lauren', 'polo', 'majica', 'navy', 'xl', 'nova', 'muška'],
    attributes: {},
    views_count: 340,
    favorites_count: 27,
    createdDaysAgo: 22,
    promoted: false,
  },
  {
    sellerKey: 'fashion_haus',
    title: 'Levi\'s 501 Original jeans 32x32 — stone wash, classic',
    description: 'Levi\'s 501 Original Cut traperice veličine 32x32. Stone wash efekt, klasični kroj ravnih nogavica. Kupljene u Levis prodavaonici. Nošene par puta, bez oštećenja. Ideal za onoga tko voli klasiku.',
    price: 55,
    currency: 'EUR',
    country: 'ba',
    categorySlug: 'odjeca',
    condition: 'like_new',
    listing_type: 'prodaja',
    images: [
      'https://picsum.photos/seed/levis501-1/800/600',
      'https://picsum.photos/seed/levis501-2/800/600',
    ],
    location: 'Mostar',
    tags: ['levis', '501', 'jeans', 'traperice', '32x32', 'stone wash'],
    attributes: {},
    views_count: 410,
    favorites_count: 33,
    createdDaysAgo: 25,
    promoted: false,
  },
  {
    sellerKey: 'fashion_haus',
    title: 'Zara dječja zimska jakna 128 — narančasta, s postavom',
    description: 'Zara Kids zimska jakna veličina 128 (7-8 god.) u narančastoj boji. Topla obloga, kapuljača, reflektirajući detalji. Nošena jednu sezonu, bez oštećenja. Izvrsna za djecu koja se igraju vani zimi.',
    price: 22,
    currency: 'EUR',
    country: 'ba',
    categorySlug: 'djeca',
    condition: 'used',
    listing_type: 'prodaja',
    images: [
      'https://picsum.photos/seed/zarakids-jakna-1/800/600',
    ],
    location: 'Mostar',
    tags: ['zara', 'djeca', 'zimska jakna', '128', 'narančasta', 'dječja'],
    attributes: {},
    views_count: 270,
    favorites_count: 19,
    createdDaysAgo: 35,
    promoted: false,
  },
];
