import type { SeedProduct } from './types.js';

// 20 cars for Premium Motors (business account)
export const CAR_PRODUCTS: SeedProduct[] = [
  {
    sellerKey: 'premiummotors',
    title: 'BMW 320d xDrive — servisna knjiga, reg. do 05/2026',
    description: 'Izvrsno očuvan BMW Serija 3, 320d xDrive. Vozilo je redovito servisirano kod ovlaštenog BMW servisa, servisna knjiga uredna i popunjena. Oprema: automatska klima, navigacija, kožna sjedišta, LED farovi, parking senzori sprijeda i straga, kamera za vožnju unatrag, Harman Kardon audio sustav, panoramski krov. Vozilo je u savršenom mehaničkom stanju. Zamjena ne dolazi u obzir. Cijena je fiksna.',
    price: 29900,
    currency: 'EUR',
    country: 'ba',
    categorySlug: 'vozila-osobni-rabljeni',
    condition: 'like_new',
    listing_type: 'prodaja',
    images: [
      'https://picsum.photos/seed/bmw320d-1/800/600',
      'https://picsum.photos/seed/bmw320d-2/800/600',
      'https://picsum.photos/seed/bmw320d-3/800/600',
    ],
    location: 'Sarajevo',
    tags: ['bmw', '320d', 'xdrive', 'diesel', 'automatik', 'navigacija', 'koža'],
    attributes: {
      marka: 'BMW', model: 'Serija 3 (320d)', godiste: 2019, km: 87000,
      motor: '2.0 TDI 140 kW', kubikaza: 1995, snaga: 140,
      gorivo: 'Dizel', mjenjac: 'Automatik', karoserija: 'Sedan', boja: 'Crna',
      pogon: '4x4 (stalni)', brVrata: '4',
      registriran: true, registracija: '05/2026',
      servisnaKnjiga: true, udareno: false, abs: true, voznoStanje: true, esp: true,
      klima: true, autoKlima: true, tempomat: true, adaptivniTempomat: true,
      kozenaSjed: true, grejanaSjed: true, elSjedistaVozac: true, elProzori: true,
      elRetrovizori: true, panoramskiKrov: true, multiVolan: true, startStop: true,
      navigacija: true, bluetooth: true, appleCarPlay: true, androidAuto: true,
      touchscreen: true, digKokpit: true, usbPort: true,
      parkSenzori: true, kameraNazad: true, laneAssist: true, autoKocenje: true,
      xenon: true, aluFelge: true, centralnaBrava: true, servoVolan: true, turbo: true,
    },
    views_count: 1240,
    favorites_count: 87,
    createdDaysAgo: 12,
    promoted: true,
  },
  {
    sellerKey: 'premiummotors',
    title: 'Mercedes-Benz C 220d AMG Line — full oprema',
    description: 'Mercedes-Benz C-klasa 220d, AMG Line paket. Vozilo dolazi s kompletnom servisnom knjigom i garantnim listom. Unutrašnjost u crnoj koži, AMG sport sjedišta, digitalni instrument panel, MBUX infotainment s touchscreen ekranom, burmester audio. Izvrsno stanje i vozno u svim uvjetima.',
    price: 34500,
    currency: 'EUR',
    country: 'ba',
    categorySlug: 'vozila-osobni-rabljeni',
    condition: 'like_new',
    listing_type: 'prodaja',
    images: [
      'https://picsum.photos/seed/mercc220d-1/800/600',
      'https://picsum.photos/seed/mercc220d-2/800/600',
      'https://picsum.photos/seed/mercc220d-3/800/600',
    ],
    location: 'Sarajevo',
    tags: ['mercedes', 'c220d', 'amg', 'diesel', 'automatik', 'burmester'],
    attributes: {
      marka: 'Mercedes-Benz', model: 'C 220d AMG Line', godiste: 2020, km: 62000,
      motor: '2.0 CDI 143 kW', kubikaza: 1950, snaga: 143,
      gorivo: 'Dizel', mjenjac: 'Automatik', karoserija: 'Sedan', boja: 'Siva',
      pogon: 'Zadnji', brVrata: '4',
      registriran: true, registracija: '11/2025',
      servisnaKnjiga: true, udareno: false, abs: true, voznoStanje: true, esp: true,
      klima: true, autoKlima: true, tempomat: true, adaptivniTempomat: true,
      kozenaSjed: true, grejanaSjed: true, ventiliranaSjed: true, elSjedistaVozac: true,
      memSjedista: true, elProzori: true, elRetrovizori: true, grijaniVolan: true,
      multiVolan: true, startStop: true, bezKljucPokr: true,
      navigacija: true, bluetooth: true, appleCarPlay: true, androidAuto: true,
      touchscreen: true, digKokpit: true, headUpDisplay: true, usbPort: true, bezicnoPunjenje: true,
      parkSenzori: true, kameraNazad: true, kamera360: true, laneAssist: true,
      mrtvitacni: true, autoKocenje: true, znakDetekt: true,
      xenon: true, matrixLed: true, dnevnaSvjetla: true, aluFelge: true,
      senzorKise: true, senzorSvjetla: true, alarm: true, centralnaBrava: true,
      servoVolan: true, turbo: true, isofix: true,
    },
    views_count: 980,
    favorites_count: 62,
    createdDaysAgo: 8,
    promoted: true,
  },
  {
    sellerKey: 'premiummotors',
    title: 'Audi A4 2.0 TDI S-Line — matrix LED, virtualni kokpit',
    description: 'Audi A4 Avant u S-Line paket. Virtualni kokpit, matrix LED farovi, quattro 4x4 pogon. Vozilo je uvezeno iz Njemačke i ima kompletnu servisnu historiju. Bez havarije, nije ni udareno ni farbano. Idealno obiteljsko vozilo.',
    price: 26800,
    currency: 'EUR',
    country: 'ba',
    categorySlug: 'vozila-osobni-rabljeni',
    condition: 'like_new',
    listing_type: 'prodaja',
    images: [
      'https://picsum.photos/seed/audia4-sline-1/800/600',
      'https://picsum.photos/seed/audia4-sline-2/800/600',
      'https://picsum.photos/seed/audia4-sline-3/800/600',
    ],
    location: 'Sarajevo',
    tags: ['audi', 'a4', 'quattro', 's-line', 'matrix', 'diesel', 'karavan'],
    attributes: {
      marka: 'Audi', model: 'A4 Avant 2.0 TDI S-Line', godiste: 2018, km: 118000,
      motor: '2.0 TDI 110 kW', kubikaza: 1968, snaga: 110,
      gorivo: 'Dizel', mjenjac: 'DSG / DCT', karoserija: 'Karavan', boja: 'Bijela',
      pogon: '4x4 (stalni)', brVrata: '5',
      registriran: true, registracija: '03/2026',
      servisnaKnjiga: true, udareno: false, abs: true, voznoStanje: true, esp: true,
      klima: true, autoKlima: true, tempomat: true, kozenaSjed: true, grejanaSjed: true,
      elProzori: true, elRetrovizori: true, multiVolan: true, startStop: true,
      navigacija: true, bluetooth: true, appleCarPlay: true, androidAuto: true,
      touchscreen: true, digKokpit: true, usbPort: true,
      parkSenzori: true, kameraNazad: true, laneAssist: true,
      xenon: true, matrixLed: true, dnevnaSvjetla: true, aluFelge: true,
      kukaPrivez: true, centralnaBrava: true, servoVolan: true, turbo: true, isofix: true,
    },
    views_count: 820,
    favorites_count: 54,
    createdDaysAgo: 20,
    promoted: false,
  },
  {
    sellerKey: 'premiummotors',
    title: 'Volkswagen Golf 8 GTI Clubsport — 300 KS, DSG',
    description: 'Golf 8 GTI Clubsport, ograničena edicija s pojačanim 2.0 TSI motorom od 300 KS. DSG7 mjenjač, sport diferencijal, performance kočioni sustav. Akrapovič ispuh. Vozilo je uvezeno iz Austrije, ima certifikat bez havarije.',
    price: 41000,
    currency: 'EUR',
    country: 'ba',
    categorySlug: 'vozila-osobni-rabljeni',
    condition: 'like_new',
    listing_type: 'prodaja',
    images: [
      'https://picsum.photos/seed/golf8gti-1/800/600',
      'https://picsum.photos/seed/golf8gti-2/800/600',
    ],
    location: 'Sarajevo',
    tags: ['vw', 'golf', 'gti', 'clubsport', 'benzin', 'dsg', 'sport'],
    attributes: {
      marka: 'Volkswagen', model: 'Golf 8 GTI Clubsport', godiste: 2021, km: 38000,
      motor: '2.0 TSI 221 kW', kubikaza: 1984, snaga: 221,
      gorivo: 'Benzin', mjenjac: 'DSG / DCT', karoserija: 'Hatchback', boja: 'Bijela',
      pogon: 'Prednji', brVrata: '5',
      registriran: true, registracija: '09/2026',
      servisnaKnjiga: true, udareno: false, abs: true, voznoStanje: true, esp: true,
      klima: true, autoKlima: true, tempomat: true, adaptivniTempomat: true,
      kozenaSjed: true, grejanaSjed: true, elProzori: true, elRetrovizori: true,
      grijaniVolan: true, multiVolan: true, startStop: true, bezKljucPokr: true,
      navigacija: true, bluetooth: true, appleCarPlay: true, androidAuto: true,
      touchscreen: true, digKokpit: true, headUpDisplay: true, usbPort: true,
      parkSenzori: true, kameraNazad: true, laneAssist: true, autoKocenje: true,
      xenon: true, matrixLed: true, dnevnaSvjetla: true, aluFelge: true,
      alarm: true, centralnaBrava: true, servoVolan: true, turbo: true,
    },
    views_count: 1680,
    favorites_count: 134,
    createdDaysAgo: 5,
    promoted: true,
  },
  {
    sellerKey: 'premiummotors',
    title: 'Porsche Cayenne 3.0 TDI — panorama, softclosing vrata',
    description: 'Porsche Cayenne diesel u izuzetnom stanju. Softclosing vrata, panoramski krov, električna sjedišta s memorijom, Bose audio sustav. Vučna kuka, ljetni i zimski kotači. Sve servisirano isključivo u Porsche servisu. Vozilo je uvezeno iz Njemačke.',
    price: 52000,
    currency: 'EUR',
    country: 'ba',
    categorySlug: 'vozila-osobni-rabljeni',
    condition: 'used',
    listing_type: 'prodaja',
    images: [
      'https://picsum.photos/seed/porschecayenne-1/800/600',
      'https://picsum.photos/seed/porschecayenne-2/800/600',
      'https://picsum.photos/seed/porschecayenne-3/800/600',
    ],
    location: 'Sarajevo',
    tags: ['porsche', 'cayenne', 'diesel', 'suv', 'bose', 'panorama'],
    attributes: {
      marka: 'Porsche', model: 'Cayenne 3.0 TDI', godiste: 2017, km: 142000,
      motor: '3.0 TDI 210 kW', kubikaza: 2967, snaga: 210,
      gorivo: 'Dizel', mjenjac: 'Automatik', karoserija: 'SUV', boja: 'Crna',
      pogon: '4x4 (stalni)', brVrata: '5',
      registriran: true, registracija: '07/2025',
      servisnaKnjiga: true, udareno: false, abs: true, voznoStanje: true, esp: true,
      klima: true, autoKlima: true, tempomat: true, adaptivniTempomat: true,
      kozenaSjed: true, grejanaSjed: true, ventiliranaSjed: true, elSjedistaVozac: true,
      memSjedista: true, elProzori: true, elRetrovizori: true, panoramskiKrov: true,
      grijaniVolan: true, multiVolan: true, startStop: true, bezKljucPokr: true,
      navigacija: true, bluetooth: true, touchscreen: true, digKokpit: true,
      headUpDisplay: true, usbPort: true,
      parkSenzori: true, kameraNazad: true, kamera360: true, laneAssist: true,
      mrtvitacni: true, xenon: true, matrixLed: true, dnevnaSvjetla: true,
      aluFelge: true, kukaPrivez: true, zatTamna: true, alarm: true,
      centralnaBrava: true, servoVolan: true, turbo: true,
    },
    views_count: 2100,
    favorites_count: 178,
    createdDaysAgo: 18,
    promoted: true,
  },
  {
    sellerKey: 'premiummotors',
    title: 'Toyota Yaris Cross 1.5 Hybrid — automatik, novi model',
    description: 'Toyota Yaris Cross hibrid, jednovremen model. Tvornički automatski mjenjač, start/stop sustav. Ekonomičan i ekološki prihvatljiv. Servisiran isključivo u Toyota servisu. Idealan gradski automobil.',
    price: 23500,
    currency: 'EUR',
    country: 'ba',
    categorySlug: 'vozila-osobni-rabljeni',
    condition: 'like_new',
    listing_type: 'prodaja',
    images: [
      'https://picsum.photos/seed/yaris-cross-1/800/600',
      'https://picsum.photos/seed/yaris-cross-2/800/600',
    ],
    location: 'Sarajevo',
    tags: ['toyota', 'yaris', 'cross', 'hibrid', 'hybrid', 'suv', 'automatik'],
    attributes: {
      marka: 'Toyota', model: 'Yaris Cross 1.5 Hybrid', godiste: 2022, km: 28000,
      motor: '1.5 Hybrid 85 kW', kubikaza: 1490, snaga: 85,
      gorivo: 'Hibrid', mjenjac: 'Automatik', karoserija: 'Crossover', boja: 'Plava',
      pogon: 'Prednji', brVrata: '5',
      registriran: true, registracija: '04/2027',
      servisnaKnjiga: true, udareno: false, abs: true, voznoStanje: true, esp: true,
      klima: true, autoKlima: true, tempomat: true, elProzori: true, elRetrovizori: true,
      multiVolan: true, startStop: true,
      navigacija: true, bluetooth: true, appleCarPlay: true, androidAuto: true,
      touchscreen: true, usbPort: true,
      parkSenzori: true, kameraNazad: true, autoKocenje: true,
      xenon: true, dnevnaSvjetla: true, aluFelge: true, centralnaBrava: true, servoVolan: true,
    },
    views_count: 540,
    favorites_count: 31,
    createdDaysAgo: 32,
    promoted: false,
  },
  {
    sellerKey: 'premiummotors',
    title: 'Škoda Octavia 2.0 TDI RS — sport paket, 200 KS',
    description: 'Škoda Octavia RS combi. Sportsko vozilo obiteljskog formata. Kompletna servisna historija, uvezena iz Češke. Sport sjedišta, DCC adaptivno vješanje, performance ispuh.',
    price: 24900,
    currency: 'EUR',
    country: 'ba',
    categorySlug: 'vozila-osobni-rabljeni',
    condition: 'used',
    listing_type: 'prodaja',
    images: [
      'https://picsum.photos/seed/octaviars-1/800/600',
      'https://picsum.photos/seed/octaviars-2/800/600',
    ],
    location: 'Sarajevo',
    tags: ['skoda', 'octavia', 'rs', 'diesel', 'sport', 'karavan', 'dsg'],
    attributes: {
      marka: 'Škoda', model: 'Octavia 2.0 TDI RS', godiste: 2019, km: 104000,
      motor: '2.0 TDI 147 kW', kubikaza: 1968, snaga: 147,
      gorivo: 'Dizel', mjenjac: 'DSG / DCT', karoserija: 'Karavan', boja: 'Crna',
      pogon: 'Prednji', brVrata: '5',
      registriran: true, registracija: '01/2026',
      servisnaKnjiga: true, udareno: false, abs: true, voznoStanje: true, esp: true,
      klima: true, autoKlima: true, tempomat: true, kozenaSjed: true, grejanaSjed: true,
      elProzori: true, elRetrovizori: true, multiVolan: true, startStop: true,
      navigacija: true, bluetooth: true, appleCarPlay: true, androidAuto: true,
      touchscreen: true, digKokpit: true, usbPort: true,
      parkSenzori: true, kameraNazad: true, laneAssist: true,
      xenon: true, dnevnaSvjetla: true, aluFelge: true, kukaPrivez: true,
      centralnaBrava: true, servoVolan: true, turbo: true, isofix: true,
    },
    views_count: 730,
    favorites_count: 44,
    createdDaysAgo: 25,
    promoted: false,
  },
  {
    sellerKey: 'premiummotors',
    title: 'Ford Mustang Mach-E AWD — električni SUV, 99 kWh',
    description: 'Ford Mustang Mach-E Extended Range AWD. Električni crossover SUV. Domet do 520 km po WLTP ciklusu. Brzo punjenje DC 150 kW. Panoramski fiksni krov, SYNC4A infotainment.',
    price: 49800,
    currency: 'EUR',
    country: 'ba',
    categorySlug: 'vozila-osobni-rabljeni',
    condition: 'like_new',
    listing_type: 'prodaja',
    images: [
      'https://picsum.photos/seed/mache-1/800/600',
      'https://picsum.photos/seed/mache-2/800/600',
    ],
    location: 'Sarajevo',
    tags: ['ford', 'mustang', 'mach-e', 'električni', 'suv', 'awd'],
    attributes: {
      marka: 'Ford', model: 'Mustang Mach-E AWD', godiste: 2022, km: 41000,
      motor: '98.7 kWh Elektromotor 216 kW', kubikaza: 0, snaga: 216,
      gorivo: 'Električni', mjenjac: 'Automatik', karoserija: 'SUV', boja: 'Bijela',
      pogon: '4x4 (stalni)', brVrata: '5',
      registriran: true, registracija: '06/2027',
      servisnaKnjiga: true, udareno: false, abs: true, voznoStanje: true, esp: true,
      klima: true, autoKlima: true, tempomat: true, adaptivniTempomat: true,
      kozenaSjed: true, grejanaSjed: true, elProzori: true, elRetrovizori: true,
      panoramskiKrov: true, multiVolan: true, bezKljucPokr: true,
      navigacija: true, bluetooth: true, appleCarPlay: true, androidAuto: true,
      touchscreen: true, digKokpit: true, usbPort: true, bezicnoPunjenje: true,
      parkSenzori: true, kameraNazad: true, kamera360: true, laneAssist: true,
      mrtvitacni: true, autoKocenje: true, znakDetekt: true,
      xenon: true, matrixLed: true, dnevnaSvjetla: true, aluFelge: true,
      alarm: true, centralnaBrava: true, servoVolan: true,
    },
    views_count: 1890,
    favorites_count: 143,
    createdDaysAgo: 9,
    promoted: true,
  },
  {
    sellerKey: 'premiummotors',
    title: 'Volvo XC60 B5 AWD Inscription — full oprema, Bowers & Wilkins',
    description: 'Volvo XC60 u Inscription paketu. Bowers & Wilkins audio sustav, koža Nappa, električna sjedišta s masažom, pilot assist, 360° kamera. Uvezeno iz Norveške, nema havarije.',
    price: 47500,
    currency: 'EUR',
    country: 'ba',
    categorySlug: 'vozila-osobni-rabljeni',
    condition: 'like_new',
    listing_type: 'prodaja',
    images: [
      'https://picsum.photos/seed/volvoxc60-1/800/600',
      'https://picsum.photos/seed/volvoxc60-2/800/600',
      'https://picsum.photos/seed/volvoxc60-3/800/600',
    ],
    location: 'Sarajevo',
    tags: ['volvo', 'xc60', 'inscription', 'awd', 'hibrid', 'suv', 'nappa'],
    attributes: {
      marka: 'Volvo', model: 'XC60 B5 AWD Inscription', godiste: 2021, km: 55000,
      motor: '2.0 B5 MHEV 183 kW', kubikaza: 1969, snaga: 183,
      gorivo: 'Hibrid', mjenjac: 'Automatik', karoserija: 'SUV', boja: 'Srebrna',
      pogon: '4x4 (stalni)', brVrata: '5',
      registriran: true, registracija: '02/2026',
      servisnaKnjiga: true, udareno: false, abs: true, voznoStanje: true, esp: true,
      klima: true, autoKlima: true, tempomat: true, adaptivniTempomat: true,
      kozenaSjed: true, grejanaSjed: true, ventiliranaSjed: true,
      elSjedistaVozac: true, memSjedista: true, masazaSjedista: true,
      elProzori: true, elRetrovizori: true, panoramskiKrov: true, grijaniVolan: true,
      multiVolan: true, startStop: true, bezKljucPokr: true,
      navigacija: true, bluetooth: true, appleCarPlay: true, androidAuto: true,
      touchscreen: true, digKokpit: true, headUpDisplay: true, usbPort: true, bezicnoPunjenje: true,
      parkSenzori: true, kameraNazad: true, kamera360: true, laneAssist: true,
      mrtvitacni: true, autoKocenje: true, znakDetekt: true, hillAssist: true,
      xenon: true, matrixLed: true, dnevnaSvjetla: true, aluFelge: true,
      kukaPrivez: true, zatTamna: true, senzorKise: true, senzorSvjetla: true,
      alarm: true, centralnaBrava: true, servoVolan: true, turbo: true, isofix: true,
    },
    views_count: 1540,
    favorites_count: 119,
    createdDaysAgo: 14,
    promoted: true,
  },
  {
    sellerKey: 'premiummotors',
    title: 'Renault Kadjar 1.5 dCi EDC — 4Control, tvorničke garancija',
    description: 'Renault Kadjar s 4Control sustavom upravljanja s 4 kotača. Tvornička garancija još 18 mjeseci. Multimedia sustav R-LINK 2, kamera za parkiranje, panoramski krov. Odlično stanje.',
    price: 19900,
    currency: 'EUR',
    country: 'ba',
    categorySlug: 'vozila-osobni-rabljeni',
    condition: 'used',
    listing_type: 'prodaja',
    images: [
      'https://picsum.photos/seed/kadjaredc-1/800/600',
      'https://picsum.photos/seed/kadjaredc-2/800/600',
    ],
    location: 'Sarajevo',
    tags: ['renault', 'kadjar', 'diesel', 'suv', 'crossover', 'panorama'],
    attributes: {
      marka: 'Renault', model: 'Kadjar 1.5 dCi EDC', godiste: 2019, km: 89000,
      motor: '1.5 dCi 110 kW', kubikaza: 1461, snaga: 110,
      gorivo: 'Dizel', mjenjac: 'Automatik', karoserija: 'SUV', boja: 'Crvena',
      pogon: 'Prednji', brVrata: '5',
      registriran: true, registracija: '10/2025',
      servisnaKnjiga: true, udareno: false, abs: true, voznoStanje: true, esp: true,
      klima: true, autoKlima: true, tempomat: true, elProzori: true, elRetrovizori: true,
      panoramskiKrov: true, multiVolan: true, startStop: true,
      navigacija: true, bluetooth: true, appleCarPlay: true, touchscreen: true, usbPort: true,
      parkSenzori: true, kameraNazad: true, dnevnaSvjetla: true, aluFelge: true,
      centralnaBrava: true, servoVolan: true, turbo: true, isofix: true,
    },
    views_count: 480,
    favorites_count: 28,
    createdDaysAgo: 40,
    promoted: false,
  },
  {
    sellerKey: 'premiummotors',
    title: 'Hyundai Tucson 1.6 T-GDI Hybrid — LED, digitalni kokpit',
    description: 'Hyundai Tucson hibrid treće generacije. Plug-in hibrid, električni domet 62 km. Digitalni kokpit 12.3", panoramski krov, wireless CarPlay. Odlična potrošnja goriva 1.4L/100km u miješanoj vožnji.',
    price: 31800,
    currency: 'EUR',
    country: 'ba',
    categorySlug: 'vozila-osobni-rabljeni',
    condition: 'like_new',
    listing_type: 'prodaja',
    images: [
      'https://picsum.photos/seed/tucsonhybrid-1/800/600',
      'https://picsum.photos/seed/tucsonhybrid-2/800/600',
    ],
    location: 'Sarajevo',
    tags: ['hyundai', 'tucson', 'hybrid', 'suv', 'plugin', 'električni'],
    attributes: {
      marka: 'Hyundai', model: 'Tucson 1.6 T-GDI PHEV', godiste: 2022, km: 34000,
      motor: '1.6 T-GDI + E-Motor 195 kW', kubikaza: 1598, snaga: 195,
      gorivo: 'Plug-in hibrid', mjenjac: 'Automatik', karoserija: 'SUV', boja: 'Siva',
      pogon: '4x4 (stalni)', brVrata: '5',
      registriran: true, registracija: '03/2027',
      servisnaKnjiga: true, udareno: false, abs: true, voznoStanje: true, esp: true,
      klima: true, autoKlima: true, tempomat: true, adaptivniTempomat: true,
      kozenaSjed: true, grejanaSjed: true, elProzori: true, elRetrovizori: true,
      panoramskiKrov: true, grijaniVolan: true, multiVolan: true, startStop: true, bezKljucPokr: true,
      navigacija: true, bluetooth: true, appleCarPlay: true, androidAuto: true,
      touchscreen: true, digKokpit: true, usbPort: true, bezicnoPunjenje: true,
      parkSenzori: true, kameraNazad: true, kamera360: true, laneAssist: true,
      mrtvitacni: true, autoKocenje: true,
      xenon: true, matrixLed: true, dnevnaSvjetla: true, aluFelge: true,
      alarm: true, centralnaBrava: true, servoVolan: true, isofix: true,
    },
    views_count: 890,
    favorites_count: 67,
    createdDaysAgo: 22,
    promoted: false,
  },
  {
    sellerKey: 'premiummotors',
    title: 'Kia Sportage 2.0 CRDI AWD — odlična servisna, zimski set',
    description: 'Kia Sportage diesel s 4x4 pogonom. Kompletna servisna historija, uključen komplet zimskih guma na čeličnim naplaticima. Koža, navigacija, podgrijana sjedišta. Ocarinjen.',
    price: 17500,
    currency: 'EUR',
    country: 'ba',
    categorySlug: 'vozila-osobni-rabljeni',
    condition: 'used',
    listing_type: 'prodaja',
    images: [
      'https://picsum.photos/seed/kiasportage-1/800/600',
      'https://picsum.photos/seed/kiasportage-2/800/600',
    ],
    location: 'Sarajevo',
    tags: ['kia', 'sportage', 'diesel', 'awd', 'suv', 'zimski kotači'],
    attributes: {
      marka: 'Kia', model: 'Sportage 2.0 CRDI AWD', godiste: 2017, km: 148000,
      motor: '2.0 CRDi 136 kW', kubikaza: 1995, snaga: 136,
      gorivo: 'Dizel', mjenjac: 'Automatik', karoserija: 'SUV', boja: 'Bijela',
      pogon: '4x4 (povremeni)', brVrata: '5',
      registriran: true, registracija: '08/2025',
      servisnaKnjiga: true, udareno: false, abs: true, voznoStanje: true, esp: true,
      klima: true, autoKlima: true, tempomat: true, kozenaSjed: true, grejanaSjed: true,
      elProzori: true, elRetrovizori: true, multiVolan: true,
      navigacija: true, bluetooth: true, touchscreen: true, usbPort: true,
      parkSenzori: true, kameraNazad: true, dnevnaSvjetla: true, aluFelge: true,
      zamGume: true, centralnaBrava: true, servoVolan: true, turbo: true, isofix: true, ocarinjen: true,
    },
    views_count: 620,
    favorites_count: 39,
    createdDaysAgo: 35,
    promoted: false,
  },
  {
    sellerKey: 'premiummotors',
    title: 'Opel Insignia Grand Sport 1.6 CDTi — Innovation, navi',
    description: 'Opel Insignia u Innovation paketu. Ergonomska AGR sjedišta, IntelliLux LED Matrix farovi, FlexRide adaptivno vješanje. Odlično obiteljsko vozilo za dugačka putovanja.',
    price: 16800,
    currency: 'EUR',
    country: 'ba',
    categorySlug: 'vozila-osobni-rabljeni',
    condition: 'used',
    listing_type: 'prodaja',
    images: [
      'https://picsum.photos/seed/insignia-1/800/600',
      'https://picsum.photos/seed/insignia-2/800/600',
    ],
    location: 'Sarajevo',
    tags: ['opel', 'insignia', 'grand sport', 'diesel', 'matrix', 'sedan'],
    attributes: {
      marka: 'Opel', model: 'Insignia Grand Sport 1.6 CDTi', godiste: 2018, km: 133000,
      motor: '1.6 CDTI 100 kW', kubikaza: 1598, snaga: 100,
      gorivo: 'Dizel', mjenjac: 'Ručni', karoserija: 'Sedan', boja: 'Siva',
      pogon: 'Prednji', brVrata: '4',
      registriran: true, registracija: '06/2025',
      servisnaKnjiga: true, udareno: false, abs: true, voznoStanje: true, esp: true,
      klima: true, autoKlima: true, tempomat: true, kozenaSjed: true, grejanaSjed: true,
      elProzori: true, elRetrovizori: true, multiVolan: true,
      navigacija: true, bluetooth: true, appleCarPlay: true, touchscreen: true, usbPort: true,
      parkSenzori: true, kameraNazad: true, xenon: true, matrixLed: true, aluFelge: true,
      centralnaBrava: true, servoVolan: true, turbo: true, isofix: true,
    },
    views_count: 390,
    favorites_count: 21,
    createdDaysAgo: 50,
    promoted: false,
  },
  {
    sellerKey: 'premiummotors',
    title: 'Nissan Qashqai 1.3 DIG-T MHEV Tekna — ProPilot, 360°',
    description: 'Nissan Qashqai treće generacije u Tekna opremi. ProPilot sustav autonomne vožnje, kamera 360°, bežično punjenje, 12.3" ekran. Najkompletnija oprema u razredu.',
    price: 28900,
    currency: 'EUR',
    country: 'ba',
    categorySlug: 'vozila-osobni-rabljeni',
    condition: 'like_new',
    listing_type: 'prodaja',
    images: [
      'https://picsum.photos/seed/qashqai-1/800/600',
      'https://picsum.photos/seed/qashqai-2/800/600',
    ],
    location: 'Sarajevo',
    tags: ['nissan', 'qashqai', 'mhev', 'hybrid', 'crossover', 'propilot'],
    attributes: {
      marka: 'Nissan', model: 'Qashqai 1.3 DIG-T MHEV Tekna', godiste: 2023, km: 18000,
      motor: '1.3 DIG-T MHEV 103 kW', kubikaza: 1332, snaga: 103,
      gorivo: 'Hibrid', mjenjac: 'DSG / DCT', karoserija: 'Crossover', boja: 'Srebrna',
      pogon: 'Prednji', brVrata: '5',
      registriran: true, registracija: '11/2027',
      servisnaKnjiga: true, udareno: false, abs: true, voznoStanje: true, esp: true,
      klima: true, autoKlima: true, tempomat: true, adaptivniTempomat: true,
      kozenaSjed: true, grejanaSjed: true, elProzori: true, elRetrovizori: true,
      grijaniVolan: true, multiVolan: true, startStop: true, bezKljucPokr: true,
      navigacija: true, bluetooth: true, appleCarPlay: true, androidAuto: true,
      touchscreen: true, digKokpit: true, usbPort: true, bezicnoPunjenje: true,
      parkSenzori: true, kameraNazad: true, kamera360: true, laneAssist: true,
      mrtvitacni: true, autoKocenje: true, znakDetekt: true,
      xenon: true, matrixLed: true, dnevnaSvjetla: true, aluFelge: true,
      alarm: true, centralnaBrava: true, servoVolan: true, turbo: true, isofix: true,
    },
    views_count: 710,
    favorites_count: 52,
    createdDaysAgo: 16,
    promoted: false,
  },
  {
    sellerKey: 'premiummotors',
    title: 'Seat Leon 1.5 eTSI FR — DSG, sportski karavan',
    description: 'Seat Leon Sportstourer FR u mild-hybrid izvedbi. DSG7 mjenjač, sport sjedišta, FR body kit, virtualni kokpit, bezžično CarPlay. Odlično obiteljsko sportsko vozilo s velikim prtljažnikom.',
    price: 22800,
    currency: 'EUR',
    country: 'ba',
    categorySlug: 'vozila-osobni-rabljeni',
    condition: 'like_new',
    listing_type: 'prodaja',
    images: [
      'https://picsum.photos/seed/seatleonfr-1/800/600',
      'https://picsum.photos/seed/seatleonfr-2/800/600',
    ],
    location: 'Sarajevo',
    tags: ['seat', 'leon', 'fr', 'etsi', 'dsg', 'karavan', 'hibrid'],
    attributes: {
      marka: 'SEAT', model: 'Leon Sportstourer 1.5 eTSI FR', godiste: 2021, km: 52000,
      motor: '1.5 eTSI MHEV 110 kW', kubikaza: 1498, snaga: 110,
      gorivo: 'Hibrid', mjenjac: 'DSG / DCT', karoserija: 'Karavan', boja: 'Crvena',
      pogon: 'Prednji', brVrata: '5',
      registriran: true, registracija: '05/2026',
      servisnaKnjiga: true, udareno: false, abs: true, voznoStanje: true, esp: true,
      klima: true, autoKlima: true, tempomat: true, elProzori: true, elRetrovizori: true,
      multiVolan: true, startStop: true,
      navigacija: true, bluetooth: true, appleCarPlay: true, androidAuto: true,
      touchscreen: true, digKokpit: true, usbPort: true, bezicnoPunjenje: true,
      parkSenzori: true, kameraNazad: true, laneAssist: true,
      xenon: true, dnevnaSvjetla: true, aluFelge: true,
      kukaPrivez: true, centralnaBrava: true, servoVolan: true, turbo: true, isofix: true,
    },
    views_count: 460,
    favorites_count: 33,
    createdDaysAgo: 28,
    promoted: false,
  },
  {
    sellerKey: 'premiummotors',
    title: 'Mazda CX-5 2.2 SkyActiv-D AWD — Takumi, BOSE audio',
    description: 'Mazda CX-5 u Takumi paketu, koji je najviši stupanj opreme. BOSE audio, koža Nappa, keramika drvo, 360° kamera. Bez havarije, uvezeno iz Japana.',
    price: 27400,
    currency: 'EUR',
    country: 'ba',
    categorySlug: 'vozila-osobni-rabljeni',
    condition: 'used',
    listing_type: 'prodaja',
    images: [
      'https://picsum.photos/seed/mazdacx5-1/800/600',
      'https://picsum.photos/seed/mazdacx5-2/800/600',
    ],
    location: 'Sarajevo',
    tags: ['mazda', 'cx5', 'diesel', 'awd', 'suv', 'bose', 'nappa'],
    attributes: {
      marka: 'Mazda', model: 'CX-5 2.2 SkyActiv-D AWD Takumi', godiste: 2020, km: 76000,
      motor: '2.2 SkyActiv-D 143 kW', kubikaza: 2191, snaga: 143,
      gorivo: 'Dizel', mjenjac: 'Automatik', karoserija: 'SUV', boja: 'Crvena',
      pogon: '4x4 (povremeni)', brVrata: '5',
      registriran: true, registracija: '09/2025',
      servisnaKnjiga: true, udareno: false, abs: true, voznoStanje: true, esp: true,
      klima: true, autoKlima: true, tempomat: true, adaptivniTempomat: true,
      kozenaSjed: true, grejanaSjed: true, ventiliranaSjed: true, elSjedistaVozac: true,
      memSjedista: true, elProzori: true, elRetrovizori: true, grijaniVolan: true,
      multiVolan: true, startStop: true, bezKljucPokr: true,
      navigacija: true, bluetooth: true, appleCarPlay: true, androidAuto: true,
      touchscreen: true, digKokpit: true, headUpDisplay: true, usbPort: true,
      parkSenzori: true, kameraNazad: true, kamera360: true, laneAssist: true,
      mrtvitacni: true, autoKocenje: true,
      xenon: true, matrixLed: true, dnevnaSvjetla: true, aluFelge: true,
      alarm: true, centralnaBrava: true, servoVolan: true, turbo: true, isofix: true,
    },
    views_count: 850,
    favorites_count: 58,
    createdDaysAgo: 30,
    promoted: false,
  },
  {
    sellerKey: 'premiummotors',
    title: 'Jeep Wrangler 3.6 V6 Rubicon — hard top, unlimited',
    description: 'Jeep Wrangler Unlimited Rubicon s benzinskim V6 motorom. Off-road legende. Električni hard-top, lokot za prednju i stražnju osovinu, terenski program. Uvoznik garantira bez havarije.',
    price: 58000,
    currency: 'EUR',
    country: 'ba',
    categorySlug: 'vozila-osobni-rabljeni',
    condition: 'used',
    listing_type: 'prodaja',
    images: [
      'https://picsum.photos/seed/wrangler-rubicon-1/800/600',
      'https://picsum.photos/seed/wrangler-rubicon-2/800/600',
    ],
    location: 'Sarajevo',
    tags: ['jeep', 'wrangler', 'rubicon', 'offroad', '4x4', 'benzin', 'unlimited'],
    attributes: {
      marka: 'Jeep', model: 'Wrangler Unlimited Rubicon 3.6 V6', godiste: 2021, km: 68000,
      motor: '3.6 V6 Pentastar 209 kW', kubikaza: 3604, snaga: 209,
      gorivo: 'Benzin', mjenjac: 'Automatik', karoserija: 'SUV', boja: 'Crna',
      pogon: '4x4 (stalni)', brVrata: '4',
      registriran: true, registracija: '04/2026',
      servisnaKnjiga: true, udareno: false, abs: true, voznoStanje: true, esp: true,
      klima: true, autoKlima: true, tempomat: true, elProzori: true, elRetrovizori: true,
      multiVolan: true,
      navigacija: true, bluetooth: true, appleCarPlay: true, androidAuto: true,
      touchscreen: true, usbPort: true,
      parkSenzori: true, kameraNazad: true,
      xenon: true, dnevnaSvjetla: true, aluFelge: true,
      alarm: true, centralnaBrava: true, servoVolan: true, turbo: false,
    },
    views_count: 2340,
    favorites_count: 187,
    createdDaysAgo: 7,
    promoted: true,
  },
  {
    sellerKey: 'premiummotors',
    title: 'Peugeot 3008 1.5 BlueHDI EAT8 GT — full paket, Focal audio',
    description: 'Peugeot 3008 u GT opremi. Focal audio sustav, panoramski krov, i-Cockpit 3D digitalni instrument, masaža sjedišta. Odlično stanje, bez havarije.',
    price: 25900,
    currency: 'EUR',
    country: 'ba',
    categorySlug: 'vozila-osobni-rabljeni',
    condition: 'like_new',
    listing_type: 'prodaja',
    images: [
      'https://picsum.photos/seed/peugeot3008-1/800/600',
      'https://picsum.photos/seed/peugeot3008-2/800/600',
    ],
    location: 'Sarajevo',
    tags: ['peugeot', '3008', 'diesel', 'suv', 'focal', 'panorama', 'gt'],
    attributes: {
      marka: 'Peugeot', model: '3008 1.5 BlueHDI GT', godiste: 2021, km: 47000,
      motor: '1.5 BlueHDI 96 kW', kubikaza: 1499, snaga: 96,
      gorivo: 'Dizel', mjenjac: 'Automatik', karoserija: 'SUV', boja: 'Siva',
      pogon: 'Prednji', brVrata: '5',
      registriran: true, registracija: '01/2026',
      servisnaKnjiga: true, udareno: false, abs: true, voznoStanje: true, esp: true,
      klima: true, autoKlima: true, tempomat: true, adaptivniTempomat: true,
      kozenaSjed: true, grejanaSjed: true, masazaSjedista: true, elSjedistaVozac: true,
      elProzori: true, elRetrovizori: true, panoramskiKrov: true, grijaniVolan: true,
      multiVolan: true, startStop: true, bezKljucPokr: true,
      navigacija: true, bluetooth: true, appleCarPlay: true, androidAuto: true,
      touchscreen: true, digKokpit: true, headUpDisplay: true, usbPort: true, bezicnoPunjenje: true,
      parkSenzori: true, kameraNazad: true, kamera360: true, laneAssist: true,
      mrtvitacni: true, autoKocenje: true,
      xenon: true, matrixLed: true, dnevnaSvjetla: true, aluFelge: true,
      alarm: true, centralnaBrava: true, servoVolan: true, turbo: true, isofix: true,
    },
    views_count: 670,
    favorites_count: 45,
    createdDaysAgo: 23,
    promoted: false,
  },
  {
    sellerKey: 'premiummotors',
    title: 'Dacia Duster 1.5 Blue dCi 115 4x4 — Prestige, zimske gume',
    description: 'Dacia Duster u Prestige paketu s 4x4 pogonom. Najpouzdaniji SUV u svom razredu. Uključen zimski set guma. Malo kilometraža za godinu dana. Savršena ponuda za planinare i ljubitelje aktivnog odmora.',
    price: 16200,
    currency: 'EUR',
    country: 'ba',
    categorySlug: 'vozila-osobni-rabljeni',
    condition: 'used',
    listing_type: 'prodaja',
    images: [
      'https://picsum.photos/seed/daciaduster-1/800/600',
      'https://picsum.photos/seed/daciaduster-2/800/600',
    ],
    location: 'Sarajevo',
    tags: ['dacia', 'duster', 'diesel', '4x4', 'suv', 'prestige'],
    attributes: {
      marka: 'Dacia', model: 'Duster 1.5 Blue dCi 4x4 Prestige', godiste: 2020, km: 78000,
      motor: '1.5 Blue dCi 85 kW', kubikaza: 1461, snaga: 85,
      gorivo: 'Dizel', mjenjac: 'Ručni', karoserija: 'SUV', boja: 'Zelena',
      pogon: '4x4 (povremeni)', brVrata: '5',
      registriran: true, registracija: '12/2025',
      servisnaKnjiga: true, udareno: false, abs: true, voznoStanje: true, esp: true,
      klima: true, autoKlima: false, tempomat: true, elProzori: true, elRetrovizori: true,
      multiVolan: true,
      navigacija: true, bluetooth: true, appleCarPlay: true, usbPort: true,
      parkSenzori: true, kameraNazad: true, dnevnaSvjetla: true, aluFelge: true,
      zamGume: true, centralnaBrava: true, servoVolan: true, turbo: true, isofix: true,
    },
    views_count: 590,
    favorites_count: 36,
    createdDaysAgo: 45,
    promoted: false,
  },
  {
    sellerKey: 'premiummotors',
    title: 'Volkswagen Transporter T6.1 4Motion — 9 mjesta, klima zona',
    description: 'Volkswagen Transporter Multivan T6.1 s devet sjedišta i AWD pogonom. Dvozonska automatska klima, multifunkcionalni volanu, parking kamere. Savršen za prenošenje obitelji ili grupe.',
    price: 38500,
    currency: 'EUR',
    country: 'ba',
    categorySlug: 'vozila-osobni-rabljeni',
    condition: 'like_new',
    listing_type: 'prodaja',
    images: [
      'https://picsum.photos/seed/vwt61-1/800/600',
      'https://picsum.photos/seed/vwt61-2/800/600',
    ],
    location: 'Sarajevo',
    tags: ['vw', 'transporter', 't6', 'multivan', 'diesel', '4motion', '9 mjesta'],
    attributes: {
      marka: 'Volkswagen', model: 'Transporter T6.1 Multivan 4Motion', godiste: 2021, km: 88000,
      motor: '2.0 TDI 150 kW', kubikaza: 1968, snaga: 150,
      gorivo: 'Dizel', mjenjac: 'DSG / DCT', karoserija: 'Minivan', boja: 'Bijela',
      pogon: '4x4 (stalni)', brVrata: '5',
      registriran: true, registracija: '07/2026',
      servisnaKnjiga: true, udareno: false, abs: true, voznoStanje: true, esp: true,
      klima: true, autoKlima: true, tempomat: true, grejanaSjed: true, elProzori: true,
      elRetrovizori: true, multiVolan: true,
      navigacija: true, bluetooth: true, appleCarPlay: true, androidAuto: true,
      touchscreen: true, usbPort: true,
      parkSenzori: true, kameraNazad: true, kamera360: true,
      xenon: true, dnevnaSvjetla: true, aluFelge: true,
      alarm: true, centralnaBrava: true, servoVolan: true, turbo: true, isofix: true,
    },
    views_count: 1120,
    favorites_count: 89,
    createdDaysAgo: 11,
    promoted: true,
  },
];
