import type { SeedProduct } from './types.js';

// 3 apartment listings for Jadran Realty (pro account)
export const REALESTATE_PRODUCTS: SeedProduct[] = [
  {
    sellerKey: 'jadran_realty',
    title: 'Luksuzni stan u centru Sarajeva — 75m², namješten, lift',
    description: 'Iznajmljuje se potpuno opremljen dvosoban stan u samom centru Sarajeva, ulica Ferhadija. Stan se nalazi na 3. katu zgrade s liftom. Kompletno opremljen novim namještajem iz 2023. godine. Kuhinja s dishwasherom, hladnjakom, mikrovalnom i kuhalom za kavu. Dnevni boravak s velikim TV-om i IPTV pretplatom. Spavaća soba s bračnim krevetom 180x200. Klima uređaj, brzi internet 500 Mbps. Dostupan odmah.',
    price: 800,
    currency: 'EUR',
    country: 'ba',
    categorySlug: 'nekr-stanovi',
    condition: 'new',
    listing_type: 'najam',
    images: [
      'https://picsum.photos/seed/stan-sarajevo-1/800/600',
      'https://picsum.photos/seed/stan-sarajevo-2/800/600',
      'https://picsum.photos/seed/stan-sarajevo-3/800/600',
      'https://picsum.photos/seed/stan-sarajevo-4/800/600',
    ],
    location: 'Sarajevo',
    tags: ['stan', 'centar', 'sarajevo', 'namješten', 'lift', 'ferhadija', 'klimatizovano'],
    attributes: {
      povrsina: 75,
      godinaIzgradnje: 2008,
      brojSoba: '2',
      brojKupatila: '1',
      kat: '3',
      ukupnoEtaza: 6,
      namjestenost: 'Namješten',
      energetskirazred: 'C',
      orijentacija: 'Jug',
      parking: 'Ulična',
      vrstaPoda: 'Parket',
      balkon: true,
      lift: true,
      podrum: false,
      internet: true,
      klimatizovano: true,
      alarm: false,
      blindiranaVrata: true,
      videoNadzor: false,
      kuciLjubimci: false,
      uknjizeno: true,
    },
    views_count: 1420,
    favorites_count: 98,
    createdDaysAgo: 6,
    promoted: true,
  },
  {
    sellerKey: 'jadran_realty',
    title: 'Trosoban stan Mostar — Špansko, 95m², garaža, terasa 20m²',
    description: 'Iznajmljuje se moderan trosoban stan u Mostaru, Špansko polje. Stan je kompletno renoviran 2024. godine. Dvije spavaće sobe, prostrani dnevni boravak, moderna kuhinja s kuhinjskim otokom. Terasa od 20m² s pogledom na Velež. Privatna garaža u prizemlju. Centralno grijanje + klima + kamin. Savršeno za obitelji. Dostupan od 1. lipnja.',
    price: 650,
    currency: 'EUR',
    country: 'ba',
    categorySlug: 'nekr-stanovi',
    condition: 'new',
    listing_type: 'najam',
    images: [
      'https://picsum.photos/seed/stan-mostar-1/800/600',
      'https://picsum.photos/seed/stan-mostar-2/800/600',
      'https://picsum.photos/seed/stan-mostar-3/800/600',
    ],
    location: 'Mostar',
    tags: ['stan', 'mostar', 'špansko', 'trosoban', 'garaža', 'terasa', 'renoviran'],
    attributes: {
      povrsina: 95,
      godinaIzgradnje: 1985,
      brojSoba: '3',
      brojKupatila: '1',
      kat: '2',
      ukupnoEtaza: 4,
      namjestenost: 'Namješten',
      energetskirazred: 'D',
      orijentacija: 'Jug',
      parking: 'Garaža',
      vrstaPoda: 'Laminat',
      balkon: true,
      lift: false,
      podrum: true,
      internet: true,
      klimatizovano: true,
      alarm: false,
      blindiranaVrata: true,
      videoNadzor: false,
      kuciLjubimci: true,
      uknjizeno: true,
    },
    views_count: 880,
    favorites_count: 71,
    createdDaysAgo: 18,
    promoted: false,
  },
  {
    sellerKey: 'jadran_realty',
    title: 'Vikend apartman Neum — 45m², prvi red mora, parking',
    description: 'Iznajmljuje se klimatizirani apartman u Neumu, prvi red mora, 50 metara od plaže. Apartman je potpuno renoviran 2023. Stan je na 1. katu privatne kuće. Kuhinja i dnevni boravak spojen, jedna spavaća soba + kauč za još 2 osobe. Parking ispred kuće. Bez doplatka za komunalije. Dostupno kratkoročno i sezonski (travanj–listopad).',
    price: 75,
    currency: 'EUR',
    country: 'ba',
    categorySlug: 'nekr-stanovi',
    condition: 'like_new',
    listing_type: 'najam_kratkorocni',
    images: [
      'https://picsum.photos/seed/apartman-neum-1/800/600',
      'https://picsum.photos/seed/apartman-neum-2/800/600',
      'https://picsum.photos/seed/apartman-neum-3/800/600',
    ],
    location: 'Neum',
    tags: ['apartman', 'neum', 'more', 'krakorocni najam', 'plaža', 'parking', 'klimatizovano'],
    attributes: {
      povrsina: 45,
      godinaIzgradnje: 1998,
      brojSoba: '1',
      brojKupatila: '1',
      kat: '1',
      ukupnoEtaza: 2,
      namjestenost: 'Namješten',
      energetskirazred: 'E',
      orijentacija: 'Jug',
      parking: 'Parkiralište',
      vrstaPoda: 'Keramika',
      balkon: true,
      lift: false,
      podrum: false,
      internet: true,
      klimatizovano: true,
      alarm: false,
      blindiranaVrata: false,
      videoNadzor: false,
      kuciLjubimci: false,
      uknjizeno: true,
    },
    views_count: 2640,
    favorites_count: 214,
    createdDaysAgo: 3,
    promoted: true,
  },
];
