import type { SeedProfile } from './types.js';

export const SEED_PROFILES: SeedProfile[] = [
  // ── BUSINESS: Auto kuća Premium Motors ────────────────────
  {
    email: 'premiummotors@mailtest.nudinadi.ba',
    username: 'premiummotors',
    full_name: 'Premium Motors d.o.o.',
    avatar_url: 'https://i.pravatar.cc/150?u=premiummotors@mailtest.nudinadi.ba',
    bio: 'Ovlašteni prodavač rabljenih vozila premium klase. U ponudi BMW, Mercedes, Audi, Volkswagen. Svaki auto prošao je tehnički pregled i servis. Dostava na teritoriji BiH i regiona.',
    phone: '+38733445566',
    location: 'Sarajevo',
    country: 'ba',
    account_type: 'business',
    email_verified: true,
    phone_verified: true,
    level: 7,
    xp: 14800,
    total_sales: 112,
    total_purchases: 3,
    rating_average: 4.8,
    followers_count: 437,
    following_count: 12,
    locale: 'bs',
    promoted_credits: 50,
    company_name: 'Premium Motors d.o.o.',
    company_logo: 'https://i.pravatar.cc/200?u=pm-logo@nudinadi.ba',
    business_verified: true,
    business_category: 'Auto kuća',
    website_url: 'https://premiummotors.ba',
    createdDaysAgo: 420,
    productsKey: 'cars',
  },

  // ── PRO: Nekretnine Jadran ────────────────────────────────
  {
    email: 'jadranrealty@mailtest.nudinadi.ba',
    username: 'jadran_realty',
    full_name: 'Jadran Nekretnine',
    avatar_url: 'https://i.pravatar.cc/150?u=jadranrealty@mailtest.nudinadi.ba',
    bio: 'Iznajmljivanje stanova i vikendica na Jadranu i u Sarajevu. Sve nekretnine su uređene i opremljene. Kratkoročni i dugoročni najam.',
    phone: '+38763112233',
    location: 'Mostar',
    country: 'ba',
    account_type: 'pro',
    email_verified: true,
    phone_verified: true,
    level: 5,
    xp: 6200,
    total_sales: 28,
    total_purchases: 0,
    rating_average: 4.9,
    followers_count: 183,
    following_count: 7,
    locale: 'bs',
    promoted_credits: 20,
    createdDaysAgo: 310,
    productsKey: 'realestate',
  },

  // ── PRO: TechZone ─────────────────────────────────────────
  {
    email: 'techzone@mailtest.nudinadi.ba',
    username: 'techzone_bh',
    full_name: 'TechZone',
    avatar_url: 'https://i.pravatar.cc/150?u=techzone@mailtest.nudinadi.ba',
    bio: 'Prodaja rabljenih i novih mobitela, laptopa i gaming opreme. Sve provjereno i s garancijom. Šaljem brzom poštom na cijelu BiH.',
    phone: '+38765223344',
    location: 'Banja Luka',
    country: 'ba',
    account_type: 'pro',
    email_verified: true,
    phone_verified: true,
    level: 5,
    xp: 5900,
    total_sales: 34,
    total_purchases: 8,
    rating_average: 4.7,
    followers_count: 214,
    following_count: 31,
    locale: 'bs',
    promoted_credits: 15,
    createdDaysAgo: 280,
    productsKey: 'tech',
  },

  // ── PRO: Fashion Haus ────────────────────────────────────
  {
    email: 'fashionhaus@mailtest.nudinadi.ba',
    username: 'fashion_haus',
    full_name: 'Fashion Haus',
    avatar_url: 'https://i.pravatar.cc/150?u=fashionhaus@mailtest.nudinadi.ba',
    bio: 'Ženska i muška odjeća premium brendova. Zara, H&M, Mango, Tommy Hilfiger i domaći dizajneri. Besplatna dostava za narudžbe iznad 100 KM.',
    phone: '+38736778899',
    location: 'Mostar',
    country: 'ba',
    account_type: 'pro',
    email_verified: true,
    phone_verified: true,
    level: 4,
    xp: 4100,
    total_sales: 19,
    total_purchases: 2,
    rating_average: 4.6,
    followers_count: 298,
    following_count: 45,
    locale: 'bs',
    promoted_credits: 10,
    createdDaysAgo: 195,
    productsKey: 'fashion',
  },

  // ── FREE USERS (26) ────────────────────────────────────────
  {
    email: 'marko.juric@mailtest.nudinadi.ba',
    username: 'marko_juric',
    full_name: 'Marko Jurić',
    avatar_url: 'https://i.pravatar.cc/150?u=marko.juric@mailtest.nudinadi.ba',
    bio: 'Hobbyist outdoor entuzijast. Prodajem opremu koja mi više ne treba.',
    phone: '+38761334455',
    location: 'Sarajevo',
    country: 'ba',
    account_type: 'free',
    email_verified: true,
    phone_verified: false,
    level: 3,
    xp: 1200,
    total_sales: 5,
    total_purchases: 12,
    rating_average: 4.4,
    followers_count: 23,
    following_count: 67,
    locale: 'bs',
    promoted_credits: 0,
    createdDaysAgo: 240,
    productsKey: 'misc_marko',
  },
  {
    email: 'aida.hadzic@mailtest.nudinadi.ba',
    username: 'aida_h',
    full_name: 'Aida Hadžić',
    avatar_url: 'https://i.pravatar.cc/150?u=aida.hadzic@mailtest.nudinadi.ba',
    bio: 'Mama dvojice dječaka. Prodajem odjeću iz koje su izrasli.',
    phone: '+38762556677',
    location: 'Mostar',
    country: 'ba',
    account_type: 'free',
    email_verified: true,
    phone_verified: false,
    level: 2,
    xp: 480,
    total_sales: 8,
    total_purchases: 15,
    rating_average: 5.0,
    followers_count: 11,
    following_count: 19,
    locale: 'bs',
    promoted_credits: 0,
    createdDaysAgo: 180,
    productsKey: 'misc_aida',
  },
  {
    email: 'pero.vidovic@mailtest.nudinadi.ba',
    username: 'pero_v',
    full_name: 'Pero Vidović',
    avatar_url: 'https://i.pravatar.cc/150?u=pero.vidovic@mailtest.nudinadi.ba',
    bio: 'Gamer koji prodaje igre i opremu.',
    phone: '+38763778899',
    location: 'Zagreb',
    country: 'hr',
    account_type: 'free',
    email_verified: true,
    phone_verified: false,
    level: 2,
    xp: 340,
    total_sales: 3,
    total_purchases: 22,
    rating_average: 4.3,
    followers_count: 8,
    following_count: 41,
    locale: 'bs',
    promoted_credits: 0,
    createdDaysAgo: 140,
    productsKey: 'misc_pero',
  },
  {
    email: 'nermina.kovac@mailtest.nudinadi.ba',
    username: 'nermina_k',
    full_name: 'Nermina Kovač',
    avatar_url: 'https://i.pravatar.cc/150?u=nermina.kovac@mailtest.nudinadi.ba',
    bio: 'Uređujem stan i prodajem stare stvari. Sve u odličnom stanju.',
    phone: '+38735990011',
    location: 'Tuzla',
    country: 'ba',
    account_type: 'free',
    email_verified: true,
    phone_verified: true,
    level: 2,
    xp: 560,
    total_sales: 6,
    total_purchases: 4,
    rating_average: 4.8,
    followers_count: 15,
    following_count: 8,
    locale: 'bs',
    promoted_credits: 0,
    createdDaysAgo: 200,
    productsKey: 'misc_nermina',
  },
  {
    email: 'damir.begic@mailtest.nudinadi.ba',
    username: 'damir_b',
    full_name: 'Damir Begić',
    avatar_url: 'https://i.pravatar.cc/150?u=damir.begic@mailtest.nudinadi.ba',
    bio: 'Student prava. Prodajem udžbenike i stručnu literaturu.',
    phone: '+38761112233',
    location: 'Banja Luka',
    country: 'ba',
    account_type: 'free',
    email_verified: true,
    phone_verified: false,
    level: 1,
    xp: 180,
    total_sales: 2,
    total_purchases: 7,
    rating_average: 5.0,
    followers_count: 4,
    following_count: 12,
    locale: 'bs',
    promoted_credits: 0,
    createdDaysAgo: 90,
    productsKey: 'misc_damir',
  },
  {
    email: 'lejla.music@mailtest.nudinadi.ba',
    username: 'lejla_music',
    full_name: 'Lejla Musić',
    avatar_url: 'https://i.pravatar.cc/150?u=lejla.music@mailtest.nudinadi.ba',
    bio: 'Ljubiteljica mode. Prodajem odjeću i torbice koje nisam nosila.',
    phone: '+38761334422',
    location: 'Sarajevo',
    country: 'ba',
    account_type: 'free',
    email_verified: true,
    phone_verified: false,
    level: 3,
    xp: 920,
    total_sales: 14,
    total_purchases: 31,
    rating_average: 4.6,
    followers_count: 67,
    following_count: 88,
    locale: 'bs',
    promoted_credits: 0,
    createdDaysAgo: 320,
    productsKey: 'misc_lejla',
  },
  {
    email: 'stefan.markovic@mailtest.nudinadi.ba',
    username: 'stefan_m',
    full_name: 'Stefan Marković',
    avatar_url: 'https://i.pravatar.cc/150?u=stefan.markovic@mailtest.nudinadi.ba',
    bio: 'Fitness trener. Prodajem staru fitnes opremu.',
    phone: '+381641234567',
    location: 'Beograd',
    country: 'rs',
    account_type: 'free',
    email_verified: true,
    phone_verified: true,
    level: 3,
    xp: 1050,
    total_sales: 9,
    total_purchases: 5,
    rating_average: 4.5,
    followers_count: 34,
    following_count: 22,
    locale: 'bs',
    promoted_credits: 0,
    createdDaysAgo: 260,
    productsKey: 'misc_stefan',
  },
  {
    email: 'ivana.peric@mailtest.nudinadi.ba',
    username: 'ivana_p',
    full_name: 'Ivana Perić',
    avatar_url: 'https://i.pravatar.cc/150?u=ivana.peric@mailtest.nudinadi.ba',
    bio: 'Glazbenica i učiteljica gitare. Prodajem instrumente iz zbirke.',
    phone: '+385912345678',
    location: 'Split',
    country: 'hr',
    account_type: 'free',
    email_verified: true,
    phone_verified: false,
    level: 2,
    xp: 410,
    total_sales: 3,
    total_purchases: 9,
    rating_average: 4.7,
    followers_count: 29,
    following_count: 54,
    locale: 'bs',
    promoted_credits: 0,
    createdDaysAgo: 155,
    productsKey: 'misc_ivana',
  },
  {
    email: 'edin.softic@mailtest.nudinadi.ba',
    username: 'edin_s',
    full_name: 'Edin Softić',
    avatar_url: 'https://i.pravatar.cc/150?u=edin.softic@mailtest.nudinadi.ba',
    bio: 'Kupujem nove, prodajem stare. Tehnika i elektronika.',
    phone: '+38761667788',
    location: 'Sarajevo',
    country: 'ba',
    account_type: 'free',
    email_verified: true,
    phone_verified: true,
    level: 3,
    xp: 1380,
    total_sales: 11,
    total_purchases: 18,
    rating_average: 4.3,
    followers_count: 42,
    following_count: 30,
    locale: 'bs',
    promoted_credits: 0,
    createdDaysAgo: 290,
    productsKey: 'misc_edin',
  },
  {
    email: 'maja.dubic@mailtest.nudinadi.ba',
    username: 'maja_d',
    full_name: 'Maja Dubić',
    avatar_url: 'https://i.pravatar.cc/150?u=maja.dubic@mailtest.nudinadi.ba',
    bio: 'Mama i domaćica. Prodajem igračke i dječju opremu.',
    phone: '+38732889900',
    location: 'Zenica',
    country: 'ba',
    account_type: 'free',
    email_verified: true,
    phone_verified: false,
    level: 2,
    xp: 620,
    total_sales: 7,
    total_purchases: 16,
    rating_average: 5.0,
    followers_count: 18,
    following_count: 24,
    locale: 'bs',
    promoted_credits: 0,
    createdDaysAgo: 210,
    productsKey: 'misc_maja',
  },
  {
    email: 'zlatko.ristic@mailtest.nudinadi.ba',
    username: 'zlatko_r',
    full_name: 'Zlatko Ristić',
    avatar_url: 'https://i.pravatar.cc/150?u=zlatko.ristic@mailtest.nudinadi.ba',
    bio: 'Auto mehaničar. Prodajem dijelove i alate.',
    phone: '+38765334455',
    location: 'Sarajevo',
    country: 'ba',
    account_type: 'free',
    email_verified: true,
    phone_verified: true,
    level: 3,
    xp: 1100,
    total_sales: 13,
    total_purchases: 6,
    rating_average: 4.2,
    followers_count: 27,
    following_count: 11,
    locale: 'bs',
    promoted_credits: 0,
    createdDaysAgo: 275,
    productsKey: 'misc_zlatko',
  },
  {
    email: 'selma.avdic@mailtest.nudinadi.ba',
    username: 'selma_a',
    full_name: 'Selma Avdić',
    avatar_url: 'https://i.pravatar.cc/150?u=selma.avdic@mailtest.nudinadi.ba',
    bio: 'Prodajem zimsku i jesensku odjeću koju nisam obukla ni jednom.',
    phone: '+38763556677',
    location: 'Mostar',
    country: 'ba',
    account_type: 'free',
    email_verified: true,
    phone_verified: false,
    level: 2,
    xp: 290,
    total_sales: 4,
    total_purchases: 13,
    rating_average: 4.5,
    followers_count: 22,
    following_count: 58,
    locale: 'bs',
    promoted_credits: 0,
    createdDaysAgo: 120,
    productsKey: 'misc_selma',
  },
  {
    email: 'filip.nikolic@mailtest.nudinadi.ba',
    username: 'filip_n',
    full_name: 'Filip Nikolić',
    avatar_url: 'https://i.pravatar.cc/150?u=filip.nikolic@mailtest.nudinadi.ba',
    bio: 'Xbox gamer koji je prešao na PS5. Prodajem Xbox opremu.',
    phone: '+385916677889',
    location: 'Zagreb',
    country: 'hr',
    account_type: 'free',
    email_verified: true,
    phone_verified: false,
    level: 2,
    xp: 350,
    total_sales: 2,
    total_purchases: 30,
    rating_average: null,
    followers_count: 6,
    following_count: 15,
    locale: 'bs',
    promoted_credits: 0,
    createdDaysAgo: 85,
    productsKey: 'misc_filip',
  },
  {
    email: 'jasmina.babic@mailtest.nudinadi.ba',
    username: 'jasmina_b',
    full_name: 'Jasmina Babić',
    avatar_url: 'https://i.pravatar.cc/150?u=jasmina.babic@mailtest.nudinadi.ba',
    bio: 'Dizajnerica enterijera. Prodajem dekorativne predmete koji ne odgovaraju novom stilu.',
    phone: '+38765778899',
    location: 'Banja Luka',
    country: 'ba',
    account_type: 'free',
    email_verified: true,
    phone_verified: false,
    level: 2,
    xp: 430,
    total_sales: 5,
    total_purchases: 9,
    rating_average: 4.8,
    followers_count: 31,
    following_count: 47,
    locale: 'bs',
    promoted_credits: 0,
    createdDaysAgo: 165,
    productsKey: 'misc_jasmina',
  },
  {
    email: 'armin.husic@mailtest.nudinadi.ba',
    username: 'armin_h',
    full_name: 'Armin Husić',
    avatar_url: 'https://i.pravatar.cc/150?u=armin.husic@mailtest.nudinadi.ba',
    bio: 'Skijaš od malih nogu. Prodajem staru skijaška opremu jer sam kupio novu sezonu.',
    phone: '+38761990011',
    location: 'Sarajevo',
    country: 'ba',
    account_type: 'free',
    email_verified: true,
    phone_verified: false,
    level: 2,
    xp: 380,
    total_sales: 4,
    total_purchases: 8,
    rating_average: 4.5,
    followers_count: 16,
    following_count: 29,
    locale: 'bs',
    promoted_credits: 0,
    createdDaysAgo: 130,
    productsKey: 'misc_armin',
  },
  {
    email: 'tina.juric@mailtest.nudinadi.ba',
    username: 'tina_j',
    full_name: 'Tina Jurić',
    avatar_url: 'https://i.pravatar.cc/150?u=tina.juric@mailtest.nudinadi.ba',
    bio: 'Kolekcionar torbica. Prodajem one koje više ne koristim.',
    phone: '+385911122334',
    location: 'Split',
    country: 'hr',
    account_type: 'free',
    email_verified: true,
    phone_verified: false,
    level: 3,
    xp: 780,
    total_sales: 10,
    total_purchases: 25,
    rating_average: 4.9,
    followers_count: 88,
    following_count: 112,
    locale: 'bs',
    promoted_credits: 0,
    createdDaysAgo: 245,
    productsKey: 'misc_tina',
  },
  {
    email: 'milos.djordic@mailtest.nudinadi.ba',
    username: 'milos_d',
    full_name: 'Miloš Đorđić',
    avatar_url: 'https://i.pravatar.cc/150?u=milos.djordic@mailtest.nudinadi.ba',
    bio: 'Fotograf amater. Prodajem staru opremu.',
    phone: '+381641567890',
    location: 'Beograd',
    country: 'rs',
    account_type: 'free',
    email_verified: true,
    phone_verified: false,
    level: 2,
    xp: 440,
    total_sales: 3,
    total_purchases: 11,
    rating_average: 4.3,
    followers_count: 19,
    following_count: 33,
    locale: 'bs',
    promoted_credits: 0,
    createdDaysAgo: 175,
    productsKey: 'misc_milos',
  },
  {
    email: 'sabina.karic@mailtest.nudinadi.ba',
    username: 'sabina_k',
    full_name: 'Sabina Karić',
    avatar_url: 'https://i.pravatar.cc/150?u=sabina.karic@mailtest.nudinadi.ba',
    bio: 'Pedagog. Prodajem dječje knjige i edukativni materijal.',
    phone: '+38735112244',
    location: 'Tuzla',
    country: 'ba',
    account_type: 'free',
    email_verified: true,
    phone_verified: false,
    level: 1,
    xp: 210,
    total_sales: 2,
    total_purchases: 5,
    rating_average: 5.0,
    followers_count: 7,
    following_count: 14,
    locale: 'bs',
    promoted_credits: 0,
    createdDaysAgo: 70,
    productsKey: 'misc_sabina',
  },
  {
    email: 'goran.petrovic@mailtest.nudinadi.ba',
    username: 'goran_p',
    full_name: 'Goran Petrović',
    avatar_url: 'https://i.pravatar.cc/150?u=goran.petrovic@mailtest.nudinadi.ba',
    bio: 'Audio entuzijast. Prodajem zvučnike i audio opremu.',
    phone: '+38765334400',
    location: 'Banja Luka',
    country: 'ba',
    account_type: 'free',
    email_verified: true,
    phone_verified: true,
    level: 2,
    xp: 520,
    total_sales: 6,
    total_purchases: 14,
    rating_average: 4.5,
    followers_count: 24,
    following_count: 38,
    locale: 'bs',
    promoted_credits: 0,
    createdDaysAgo: 195,
    productsKey: 'misc_goran',
  },
  {
    email: 'emina.mehic@mailtest.nudinadi.ba',
    username: 'emina_m',
    full_name: 'Emina Mehić',
    avatar_url: 'https://i.pravatar.cc/150?u=emina.mehic@mailtest.nudinadi.ba',
    bio: 'Medicinska sestra. Prodajem stručnu literaturu i udžbenike.',
    phone: '+38761778899',
    location: 'Sarajevo',
    country: 'ba',
    account_type: 'free',
    email_verified: true,
    phone_verified: false,
    level: 1,
    xp: 160,
    total_sales: 1,
    total_purchases: 8,
    rating_average: 5.0,
    followers_count: 3,
    following_count: 10,
    locale: 'bs',
    promoted_credits: 0,
    createdDaysAgo: 55,
    productsKey: 'misc_emina',
  },
  {
    email: 'luka.susic@mailtest.nudinadi.ba',
    username: 'luka_s',
    full_name: 'Luka Sušić',
    avatar_url: 'https://i.pravatar.cc/150?u=luka.susic@mailtest.nudinadi.ba',
    bio: 'Street skater. Mijenjam opremu svake sezone.',
    phone: '+385919988776',
    location: 'Zagreb',
    country: 'hr',
    account_type: 'free',
    email_verified: true,
    phone_verified: false,
    level: 1,
    xp: 230,
    total_sales: 2,
    total_purchases: 7,
    rating_average: null,
    followers_count: 9,
    following_count: 21,
    locale: 'bs',
    promoted_credits: 0,
    createdDaysAgo: 65,
    productsKey: 'misc_luka',
  },
  {
    email: 'nina.vasic@mailtest.nudinadi.ba',
    username: 'nina_v',
    full_name: 'Nina Vasić',
    avatar_url: 'https://i.pravatar.cc/150?u=nina.vasic@mailtest.nudinadi.ba',
    bio: 'Zlatarka i kolekcionar nakita. Prodajem ručno rađen srebrni nakit.',
    phone: '+381641234900',
    location: 'Novi Sad',
    country: 'rs',
    account_type: 'free',
    email_verified: true,
    phone_verified: false,
    level: 2,
    xp: 640,
    total_sales: 8,
    total_purchases: 3,
    rating_average: 4.9,
    followers_count: 76,
    following_count: 29,
    locale: 'bs',
    promoted_credits: 0,
    createdDaysAgo: 220,
    productsKey: 'misc_nina',
  },
  {
    email: 'haris.tihic@mailtest.nudinadi.ba',
    username: 'haris_t',
    full_name: 'Haris Tihić',
    avatar_url: 'https://i.pravatar.cc/150?u=haris.tihic@mailtest.nudinadi.ba',
    bio: 'Prodajem kućanske aparate koji mi više ne trebaju.',
    phone: '+38761556677',
    location: 'Sarajevo',
    country: 'ba',
    account_type: 'free',
    email_verified: true,
    phone_verified: false,
    level: 1,
    xp: 190,
    total_sales: 2,
    total_purchases: 6,
    rating_average: 4.0,
    followers_count: 5,
    following_count: 8,
    locale: 'bs',
    promoted_credits: 0,
    createdDaysAgo: 80,
    productsKey: 'misc_haris',
  },
  {
    email: 'kristina.lesic@mailtest.nudinadi.ba',
    username: 'kristina_l',
    full_name: 'Kristina Lešić',
    avatar_url: 'https://i.pravatar.cc/150?u=kristina.lesic@mailtest.nudinadi.ba',
    bio: 'Dizajnerica. Prodajem tepihe i dekorativne predmete.',
    phone: '+385915544332',
    location: 'Zagreb',
    country: 'hr',
    account_type: 'free',
    email_verified: true,
    phone_verified: false,
    level: 2,
    xp: 370,
    total_sales: 4,
    total_purchases: 10,
    rating_average: 4.8,
    followers_count: 28,
    following_count: 43,
    locale: 'bs',
    promoted_credits: 0,
    createdDaysAgo: 145,
    productsKey: 'misc_kristina',
  },
  {
    email: 'ismar.omerovic@mailtest.nudinadi.ba',
    username: 'ismar_o',
    full_name: 'Ismar Omerović',
    avatar_url: 'https://i.pravatar.cc/150?u=ismar.omerovic@mailtest.nudinadi.ba',
    bio: 'Mijenjam gume svake sezone. Prodajem letnje i zimske.',
    phone: '+38761997788',
    location: 'Sarajevo',
    country: 'ba',
    account_type: 'free',
    email_verified: true,
    phone_verified: true,
    level: 2,
    xp: 580,
    total_sales: 7,
    total_purchases: 4,
    rating_average: 4.4,
    followers_count: 13,
    following_count: 6,
    locale: 'bs',
    promoted_credits: 0,
    createdDaysAgo: 185,
    productsKey: 'misc_ismar',
  },
  {
    email: 'ana.bebic@mailtest.nudinadi.ba',
    username: 'ana_b',
    full_name: 'Ana Bebić',
    avatar_url: 'https://i.pravatar.cc/150?u=ana.bebic@mailtest.nudinadi.ba',
    bio: 'Majka troje djece. Prodajem odjeću i obuću iz koje su izrasli.',
    phone: '+385913344556',
    location: 'Osijek',
    country: 'hr',
    account_type: 'free',
    email_verified: true,
    phone_verified: false,
    level: 2,
    xp: 480,
    total_sales: 6,
    total_purchases: 19,
    rating_average: 4.7,
    followers_count: 14,
    following_count: 22,
    locale: 'bs',
    promoted_credits: 0,
    createdDaysAgo: 175,
    productsKey: 'misc_ana',
  },
];
